"""
IPAWAS Data Population - Members App (Part 2 of 2)
Creates remaining 6 Member States: Guinea, Guinea-Bissau, Liberia, Senegal, Sierra Leone, Togo
"""

import os
from decimal import Decimal

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from django.utils.text import slugify

from members.models import MemberStateIPA


def create_remaining_member_states():
    """Create remaining 6 Member States"""
    print("\n" + "=" * 60)
    print("CREATING REMAINING MEMBER STATES")
    print("=" * 60)

    member_states_data = [
        {
            "country_name": "Guinea",
            "country_code": "GN",
            "slug": "guinea",
            "ipa_full_name": "Guinea Development Board",
            "ipa_acronym": "GDB",
            "tagline": "Mineral Rich Investment Frontier",
            "overview": "Guinea is endowed with vast mineral resources including bauxite, gold, and iron ore, with a population of 14.5 million and GDP of USD 21.7 billion. The Guinea Development Board supports investment facilitation and business climate improvement. The country offers significant opportunities in mining, energy, and agriculture.",
            # 'why_invest': 'World\'s largest bauxite reserves, hydropower potential, agricultural land, and growing infrastructure',
            "contact_email": "contact@invest.gov.gn",
            "contact_phone": "+224 622 00 00 00",
            "ipa_website": "https://www.invest.gov.gn",
            "physical_address": "Conakry, Guinea",
            "capital_city": "Conakry",
            "official_language": "French",
            "currency_code": "GNF",
            "currency_symbol": "FG",
            "time_zone": "GMT",
            "flag_emoji": "🇬🇳",
            "population": 14500000,
            "population_growth": Decimal("2.8"),
            "gdp": Decimal("21700000000"),
            "gdp_growth_rate": Decimal("5.6"),
            "gdp_per_capita": Decimal("1500"),
            "inflation_rate": Decimal("9.8"),
            "median_age": Decimal("18.7"),
            "urbanization_rate": Decimal("37.0"),
            "literacy_rate": Decimal("32.0"),
            "ease_of_doing_business_rank": 156,
            "fdi_inflows": Decimal("890.00"),
            "corporate_tax_rate": Decimal("35.0"),
            "days_to_start_business": 23,
            "total_exports": Decimal("4200.00"),
            "total_imports": Decimal("3800.00"),
            "key_industries": "Mining (Bauxite, Gold), Agriculture, Energy, Construction",
            "trade_agreements": "ECOWAS, AfCFTA, WTO",
            "electricity_access": Decimal("45.0"),
            "internet_penetration": Decimal("30.0"),
            "paved_roads_percent": Decimal("10.0"),
            "number_of_airports": 16,
            "is_active": True,
            "featured": False,
            "display_order": 70,
        },
        {
            "country_name": "Guinea-Bissau",
            "country_code": "GW",
            "slug": "guinea-bissau",
            "ipa_full_name": "Guiné-Bissau Investimentos",
            "ipa_acronym": "GBI",
            "tagline": "Untapped Potential in West Africa",
            "overview": "Guinea-Bissau is a coastal nation with population of 2.1 million and GDP of USD 2.1 billion. GBI promotes private investment and economic diversification. The country offers opportunities in cashew processing, fisheries, and tourism, with significant untapped potential.",
            # 'why_invest': 'Cashew production, fisheries potential, coastal tourism opportunities, and emerging investment climate',
            "contact_email": "info@gbi-invest.gw",
            "contact_phone": "+245 955 555 555",
            "ipa_website": "https://www.cpi-guineabissau.com",
            "physical_address": "Bissau, Guinea-Bissau",
            "capital_city": "Bissau",
            "official_language": "Portuguese",
            "currency_code": "XOF",
            "currency_symbol": "CFA",
            "time_zone": "GMT",
            "flag_emoji": "🇬🇼",
            "population": 2100000,
            "population_growth": Decimal("2.4"),
            "gdp": Decimal("2100000000"),
            "gdp_growth_rate": Decimal("3.8"),
            "gdp_per_capita": Decimal("1000"),
            "inflation_rate": Decimal("2.9"),
            "median_age": Decimal("19.0"),
            "urbanization_rate": Decimal("45.0"),
            "literacy_rate": Decimal("46.0"),
            "ease_of_doing_business_rank": 175,
            "fdi_inflows": Decimal("45.00"),
            "corporate_tax_rate": Decimal("25.0"),
            "days_to_start_business": 42,
            "total_exports": Decimal("280.00"),
            "total_imports": Decimal("380.00"),
            "key_industries": "Cashew, Fisheries, Agriculture, Forestry",
            "trade_agreements": "ECOWAS, WAEMU, AfCFTA",
            "electricity_access": Decimal("27.0"),
            "internet_penetration": Decimal("12.0"),
            "paved_roads_percent": Decimal("10.0"),
            "number_of_airports": 8,
            "is_active": True,
            "featured": False,
            "display_order": 80,
        },
        {
            "country_name": "Liberia",
            "country_code": "LR",
            "slug": "liberia",
            "ipa_full_name": "National Investment Commission",
            "ipa_acronym": "NIC",
            "tagline": "Africa's Fastest Growing Economy",
            "overview": "Liberia is a resource-rich nation with population of 5.5 million and GDP of USD 5.1 billion. The National Investment Commission promotes domestic and foreign investment, driving private sector development and industrial diversification. Key sectors include agriculture, mining, and forestry.",
            # 'why_invest': 'Natural resources, English-speaking, strategic port location, investment-friendly reforms',
            "contact_email": "info@nic.gov.lr",
            "contact_phone": "+231 886 555 000",
            "ipa_website": "https://www.nic.gov.lr",
            "physical_address": "Monrovia, Liberia",
            "capital_city": "Monrovia",
            "official_language": "English",
            "currency_code": "LRD",
            "currency_symbol": "$",
            "time_zone": "GMT",
            "flag_emoji": "🇱🇷",
            "population": 5500000,
            "population_growth": Decimal("2.4"),
            "gdp": Decimal("5100000000"),
            "gdp_growth_rate": Decimal("4.8"),
            "gdp_per_capita": Decimal("930"),
            "inflation_rate": Decimal("7.9"),
            "median_age": Decimal("18.3"),
            "urbanization_rate": Decimal("53.0"),
            "literacy_rate": Decimal("48.0"),
            "ease_of_doing_business_rank": 174,
            "fdi_inflows": Decimal("340.00"),
            "corporate_tax_rate": Decimal("25.0"),
            "days_to_start_business": 45,
            "total_exports": Decimal("1200.00"),
            "total_imports": Decimal("2800.00"),
            "key_industries": "Rubber, Iron Ore, Timber, Palm Oil, Maritime Services",
            "trade_agreements": "ECOWAS, AfCFTA, WTO",
            "electricity_access": Decimal("28.0"),
            "internet_penetration": Decimal("34.0"),
            "paved_roads_percent": Decimal("6.0"),
            "number_of_airports": 29,
            "is_active": True,
            "featured": False,
            "display_order": 90,
        },
        {
            "country_name": "Senegal",
            "country_code": "SN",
            "slug": "senegal",
            "ipa_full_name": "Agence de la Promotion des Investissements et des Grands Travaux",
            "ipa_acronym": "APIX",
            "tagline": "Porte d'Entrée de l'Afrique de l'Ouest",
            "overview": "Senegal is a democratic and stable nation with population of 18.6 million and GDP of USD 36.9 billion. APIX promotes private investment and manages major infrastructure projects. With recent oil and gas discoveries and world-class infrastructure, Senegal is emerging as a top investment destination.",
            # 'why_invest': 'Political stability, strategic location, new oil & gas sector, excellent infrastructure, and business-friendly reforms',
            "contact_email": "contact@investinsenegal.com",
            "contact_phone": "+221 33 849 05 55",
            "ipa_website": "https://www.investinsenegal.com",
            "physical_address": "Dakar, Senegal",
            "capital_city": "Dakar",
            "official_language": "French",
            "currency_code": "XOF",
            "currency_symbol": "CFA",
            "time_zone": "GMT",
            "flag_emoji": "🇸🇳",
            "population": 18600000,
            "population_growth": Decimal("2.7"),
            "gdp": Decimal("36900000000"),
            "gdp_growth_rate": Decimal("8.1"),
            "gdp_per_capita": Decimal("1980"),
            "inflation_rate": Decimal("5.9"),
            "median_age": Decimal("19.0"),
            "urbanization_rate": Decimal("49.0"),
            "literacy_rate": Decimal("52.0"),
            "ease_of_doing_business_rank": 123,
            "fdi_inflows": Decimal("1520.00"),
            "corporate_tax_rate": Decimal("30.0"),
            "days_to_start_business": 6,
            "total_exports": Decimal("4800.00"),
            "total_imports": Decimal("9200.00"),
            "key_industries": "Oil & Gas, Fisheries, Tourism, Agriculture, Construction, ICT",
            "trade_agreements": "ECOWAS, WAEMU, AfCFTA, EPA",
            "electricity_access": Decimal("68.0"),
            "internet_penetration": Decimal("58.0"),
            "paved_roads_percent": Decimal("16.0"),
            "number_of_airports": 20,
            "is_active": True,
            "featured": True,
            "display_order": 100,
        },
        {
            "country_name": "Sierra Leone",
            "country_code": "SL",
            "slug": "sierra-leone",
            "ipa_full_name": "National Investment Board",
            "ipa_acronym": "NIB-SL",
            "tagline": "Sweet Salone - Open for Business",
            "overview": "Sierra Leone is a resource-rich nation with population of 8.8 million and GDP of USD 6.7 billion. The National Investment Board promotes investment and exports, focusing on private sector growth and economic diversification. The country offers opportunities in agriculture, mining, tourism, and renewable energy.",
            # 'why_invest': 'Natural resources, English-speaking, coastal location, mineral wealth, and tourism potential',
            "contact_email": "info@nib.gov.sl",
            "contact_phone": "+232 76 617 617",
            "ipa_website": "https://www.nib.gov.sl",
            "physical_address": "Freetown, Sierra Leone",
            "capital_city": "Freetown",
            "official_language": "English",
            "currency_code": "SLE",
            "currency_symbol": "Le",
            "time_zone": "GMT",
            "flag_emoji": "🇸🇱",
            "population": 8800000,
            "population_growth": Decimal("2.1"),
            "gdp": Decimal("6700000000"),
            "gdp_growth_rate": Decimal("3.2"),
            "gdp_per_capita": Decimal("760"),
            "inflation_rate": Decimal("14.8"),
            "median_age": Decimal("19.0"),
            "urbanization_rate": Decimal("43.0"),
            "literacy_rate": Decimal("43.0"),
            "ease_of_doing_business_rank": 163,
            "fdi_inflows": Decimal("180.00"),
            "corporate_tax_rate": Decimal("30.0"),
            "days_to_start_business": 12,
            "total_exports": Decimal("1400.00"),
            "total_imports": Decimal("2100.00"),
            "key_industries": "Mining (Diamonds, Iron Ore), Agriculture, Fisheries, Tourism",
            "trade_agreements": "ECOWAS, AfCFTA, WTO",
            "electricity_access": Decimal("26.0"),
            "internet_penetration": Decimal("23.0"),
            "paved_roads_percent": Decimal("8.0"),
            "number_of_airports": 10,
            "is_active": True,
            "featured": False,
            "display_order": 110,
        },
        {
            "country_name": "Togo",
            "country_code": "TG",
            "slug": "togo",
            "ipa_full_name": "Agence de Promotion des Investissements et de la Zone Franche",
            "ipa_acronym": "API-ZF",
            "tagline": "West Africa's Logistics Hub",
            "overview": "Togo is strategically positioned with population of 9.3 million and GDP of USD 9.8 billion. API-ZF facilitates investment and manages free zone development. The modern Port of Lomé and excellent infrastructure make Togo a regional logistics and manufacturing hub.",
            # 'why_invest': 'Modern port infrastructure, strategic location, free trade zones, and streamlined business processes',
            "contact_email": "info@investintogo.tg",
            "contact_phone": "+228 22 23 40 00",
            "ipa_website": "https://www.investintogo.tg",
            "physical_address": "Lomé, Togo",
            "capital_city": "Lomé",
            "official_language": "French",
            "currency_code": "XOF",
            "currency_symbol": "CFA",
            "time_zone": "GMT",
            "flag_emoji": "🇹🇬",
            "population": 9300000,
            "population_growth": Decimal("2.4"),
            "gdp": Decimal("9800000000"),
            "gdp_growth_rate": Decimal("5.5"),
            "gdp_per_capita": Decimal("1050"),
            "inflation_rate": Decimal("4.5"),
            "median_age": Decimal("20.0"),
            "urbanization_rate": Decimal("43.0"),
            "literacy_rate": Decimal("63.0"),
            "ease_of_doing_business_rank": 97,
            "fdi_inflows": Decimal("280.00"),
            "corporate_tax_rate": Decimal("27.0"),
            "days_to_start_business": 8,
            "total_exports": Decimal("1700.00"),
            "total_imports": Decimal("3200.00"),
            "key_industries": "Port & Logistics, Phosphate, Agriculture, Manufacturing, Construction",
            "trade_agreements": "ECOWAS, WAEMU, AfCFTA",
            "electricity_access": Decimal("52.0"),
            "internet_penetration": Decimal("27.0"),
            "paved_roads_percent": Decimal("21.0"),
            "number_of_airports": 8,
            "is_active": True,
            "featured": False,
            "display_order": 120,
        },
    ]

    # Create member states
    for data in member_states_data:
        ms, created = MemberStateIPA.objects.get_or_create(slug=data["slug"], defaults=data)
        status = "✓ Created" if created else "- Exists"
        print(f"{status}: {ms.country_name} ({ms.ipa_acronym})")

    return MemberStateIPA.objects.all()


if __name__ == "__main__":
    member_states = create_remaining_member_states()

    print("\n" + "=" * 60)
    print("MEMBERS DATA POPULATION (Part 2) COMPLETE")
    print("=" * 60)
    print(f"\nTotal Member States: {member_states.count()}")
    print("=" * 60)
