"""
IPAWAS Data Population - Members App (Part 1 of 2)
Creates all 12 Member State IPAs with comprehensive data
"""

import os
from datetime import datetime, timedelta
from decimal import Decimal

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from django.contrib.auth import get_user_model

from core.models import Sector
from members.models import (
    FDIDataPoint,
    InvestmentIncentive,
    InvestorInquiry,
    IPAStaff,
    MemberStateIPA,
    MemberStateSector,
    SuccessStory,
)

User = get_user_model()


def create_member_states():
    """Create all 12 ECOWAS Member State IPAs"""
    print("\n" + "=" * 60)
    print("CREATING MEMBER STATES")
    print("=" * 60)

    member_states_data = [
        {
            "country_name": "Nigeria",
            "country_code": "NG",
            "slug": "nigeria",
            "ipa_full_name": "Nigerian Investment Promotion Commission",
            "ipa_acronym": "NIPC",
            "tagline": "Gateway to West Africa",
            "overview": "Nigeria is West Africa's largest economy with a GDP of USD 252 billion and a population of 227 million. The Nigerian Investment Promotion Commission (NIPC) was established to encourage, promote and coordinate investments in the Nigerian economy. NIPC serves as the One-Stop Agency for business establishment with foreign involvement and operates a One Stop Investment Center (OSIC) housing 17 government agencies.",
            # "why_invest": "Largest consumer market in Africa, strategic location, abundant natural resources, diversified economy, and growing middle class",
            "contact_email": "info@nipc.gov.ng",
            "contact_phone": "+234 906 204 0061",
            "ipa_website": "https://www.nipc.gov.ng",
            "physical_address": "Plot 1181, Aguiyi Ironsi Street, Maitama District, Abuja FCT, Nigeria",
            "capital_city": "Abuja",
            "official_language": "English",
            "currency_code": "NGN",
            "currency_symbol": "₦",
            "time_zone": "WAT",
            "flag_emoji": "🇳🇬",
            "population": 227000000,
            "population_growth": Decimal("2.5"),
            "gdp": Decimal("252000000000"),
            "gdp_growth_rate": Decimal("2.9"),
            "gdp_per_capita": Decimal("1110"),
            "inflation_rate": Decimal("21.8"),
            "median_age": Decimal("18.5"),
            "urbanization_rate": Decimal("52.0"),
            "literacy_rate": Decimal("62.0"),
            "ease_of_doing_business_rank": 131,
            "fdi_inflows": Decimal("2500.00"),
            "corporate_tax_rate": Decimal("30.0"),
            "days_to_start_business": 30,
            "total_exports": Decimal("45000.00"),
            "total_imports": Decimal("42000.00"),
            "key_industries": "Oil & Gas, Agriculture, Manufacturing, Services, Telecommunications, Banking, Construction",
            "trade_agreements": "ECOWAS, AfCFTA, WTO",
            "electricity_access": Decimal("55.0"),
            "internet_penetration": Decimal("42.0"),
            "paved_roads_percent": Decimal("15.0"),
            "number_of_airports": 26,
            "is_active": True,
            "featured": True,
            "display_order": 10,
            "linkedin_url": "https://linkedin.com/company/nigerian-investment-promotion-commission",
            "twitter_url": "https://twitter.com/nipc_ng",
            "facebook_url": "https://facebook.com/nipc.ng",
        },
        {
            "country_name": "Ghana",
            "country_code": "GH",
            "slug": "ghana",
            "ipa_full_name": "Ghana Investment Promotion Centre",
            "ipa_acronym": "GIPC",
            "tagline": "Gateway to West Africa's Golden Opportunities",
            "overview": "Ghana is one of West Africa's most stable democracies with a GDP of USD 87.5 billion and population of 33.8 million. The Ghana Investment Promotion Centre (GIPC) was established under Act 865 to promote and facilitate investments across all sectors. GIPC provides one-stop shop services and has positioned Ghana as an attractive investment destination.",
            # "why_invest": "Political stability, robust legal framework, English-speaking, strategic location, and business-friendly environment",
            "contact_email": "info@gipcghana.com",
            "contact_phone": "+233 302 665125",
            "ipa_website": "https://www.gipcghana.com",
            "physical_address": "Public Services Commission Building, Near Kinbu Secondary School, Ministries, Accra, Ghana",
            "capital_city": "Accra",
            "official_language": "English",
            "currency_code": "GHS",
            "currency_symbol": "₵",
            "time_zone": "GMT",
            "flag_emoji": "🇬🇭",
            "population": 33800000,
            "population_growth": Decimal("2.1"),
            "gdp": Decimal("87500000000"),
            "gdp_growth_rate": Decimal("5.4"),
            "gdp_per_capita": Decimal("2590"),
            "inflation_rate": Decimal("15.7"),
            "median_age": Decimal("21.5"),
            "urbanization_rate": Decimal("58.0"),
            "literacy_rate": Decimal("79.0"),
            "ease_of_doing_business_rank": 118,
            "fdi_inflows": Decimal("1850.00"),
            "corporate_tax_rate": Decimal("25.0"),
            "days_to_start_business": 14,
            "total_exports": Decimal("18000.00"),
            "total_imports": Decimal("15000.00"),
            "key_industries": "Gold Mining, Cocoa, Oil & Gas, Manufacturing, Services, ICT",
            "trade_agreements": "ECOWAS, AfCFTA, WTO, EPA",
            "electricity_access": Decimal("85.0"),
            "internet_penetration": Decimal("68.0"),
            "paved_roads_percent": Decimal("21.0"),
            "number_of_airports": 11,
            "is_active": True,
            "featured": True,
            "display_order": 20,
        },
        {
            "country_name": "Benin",
            "country_code": "BJ",
            "slug": "benin",
            "ipa_full_name": "Agence de Promotion des Investissements et des Exportations",
            "ipa_acronym": "APIEX",
            "tagline": "Carrefour de l'Afrique de l'Ouest",
            "overview": "Benin is strategically located as a gateway to West African markets with a population of 13.4 million and GDP of USD 20.5 billion. APIEX promotes and facilitates investment and exports, serving as the country's one-stop investment platform. Benin focuses on agriculture, port infrastructure, and regional trade.",
            # "why_invest": "Strategic location, port access, political stability, growing economy, and regional trade hub",
            "contact_email": "contact@apiex.bj",
            "contact_phone": "+229 21 30 00 50",
            "ipa_website": "https://www.apiex.bj",
            "physical_address": "Cotonou, Benin",
            "capital_city": "Porto-Novo",
            "official_language": "French",
            "currency_code": "XOF",
            "currency_symbol": "CFA",
            "time_zone": "WAT",
            "flag_emoji": "🇧🇯",
            "population": 13400000,
            "population_growth": Decimal("2.7"),
            "gdp": Decimal("20500000000"),
            "gdp_growth_rate": Decimal("6.3"),
            "gdp_per_capita": Decimal("1530"),
            "inflation_rate": Decimal("3.4"),
            "median_age": Decimal("19.0"),
            "urbanization_rate": Decimal("49.0"),
            "literacy_rate": Decimal("42.0"),
            "ease_of_doing_business_rank": 149,
            "fdi_inflows": Decimal("420.00"),
            "corporate_tax_rate": Decimal("30.0"),
            "days_to_start_business": 7,
            "total_exports": Decimal("3200.00"),
            "total_imports": Decimal("4800.00"),
            "key_industries": "Cotton, Port Services, Agriculture, Textiles, Construction",
            "trade_agreements": "ECOWAS, WAEMU, AfCFTA",
            "electricity_access": Decimal("42.0"),
            "internet_penetration": Decimal("35.0"),
            "paved_roads_percent": Decimal("9.0"),
            "number_of_airports": 5,
            "is_active": True,
            "featured": False,
            "display_order": 30,
        },
        {
            "country_name": "Cabo Verde",
            "country_code": "CV",
            "slug": "cabo-verde",
            "ipa_full_name": "Cabo Verde TradeInvest",
            "ipa_acronym": "CVTI",
            "tagline": "Atlantic Investment Gateway",
            "overview": "Cabo Verde is an island nation with a population of 600,000 and GDP of USD 3.2 billion. Cabo Verde TradeInvest facilitates investment across the archipelago, focusing on tourism, renewable energy, and ICT. The country offers a stable political environment and strategic Atlantic location.",
            # "why_invest": "Political stability, island tourism potential, renewable energy capacity, and strategic location",
            "contact_email": "info@cvtradeinvest.cv",
            "contact_phone": "+238 260 36 50",
            "ipa_website": "https://www.cvtradeinvest.cv",
            "physical_address": "Praia, Cabo Verde",
            "capital_city": "Praia",
            "official_language": "Portuguese",
            "currency_code": "CVE",
            "currency_symbol": "$",
            "time_zone": "CVT",
            "flag_emoji": "🇨🇻",
            "population": 600000,
            "population_growth": Decimal("1.2"),
            "gdp": Decimal("3200000000"),
            "gdp_growth_rate": Decimal("4.5"),
            "gdp_per_capita": Decimal("5330"),
            "inflation_rate": Decimal("4.0"),
            "median_age": Decimal("26.0"),
            "urbanization_rate": Decimal("67.0"),
            "literacy_rate": Decimal("87.0"),
            "ease_of_doing_business_rank": 137,
            "fdi_inflows": Decimal("110.00"),
            "corporate_tax_rate": Decimal("22.0"),
            "days_to_start_business": 10,
            "total_exports": Decimal("320.00"),
            "total_imports": Decimal("1100.00"),
            "key_industries": "Tourism, Fisheries, Renewable Energy, Services",
            "trade_agreements": "ECOWAS, WTO, Special Partnership with EU",
            "electricity_access": Decimal("95.0"),
            "internet_penetration": Decimal("64.0"),
            "paved_roads_percent": Decimal("78.0"),
            "number_of_airports": 9,
            "is_active": True,
            "featured": False,
            "display_order": 40,
        },
        {
            "country_name": "Côte d'Ivoire",
            "country_code": "CI",
            "slug": "cote-divoire",
            "ipa_full_name": "Centre de Promotion des Investissements en Côte d'Ivoire",
            "ipa_acronym": "CEPICI",
            "tagline": "West Africa's Economic Powerhouse",
            "overview": "Côte d'Ivoire is West Africa's second-largest economy with GDP of USD 82.6 billion and population of 29.2 million. CEPICI provides one-stop shop services for business registration and investment facilitation. The country is a leading producer of cocoa and cashew, with strong manufacturing and infrastructure sectors.",
            # "why_invest": "Fast-growing economy, modern infrastructure, regional business hub, and political stability",
            "contact_email": "info@cepici.gouv.ci",
            "contact_phone": "+225 27 20 31 14 00",
            "ipa_website": "https://www.cepici.gouv.ci",
            "physical_address": "Abidjan-Plateau, Côte d'Ivoire",
            "capital_city": "Yamoussoukro",
            "official_language": "French",
            "currency_code": "XOF",
            "currency_symbol": "CFA",
            "time_zone": "GMT",
            "flag_emoji": "🇨🇮",
            "population": 29200000,
            "population_growth": Decimal("2.3"),
            "gdp": Decimal("82600000000"),
            "gdp_growth_rate": Decimal("6.7"),
            "gdp_per_capita": Decimal("2830"),
            "inflation_rate": Decimal("4.2"),
            "median_age": Decimal("19.9"),
            "urbanization_rate": Decimal("52.0"),
            "literacy_rate": Decimal("47.0"),
            "ease_of_doing_business_rank": 110,
            "fdi_inflows": Decimal("1690.00"),
            "corporate_tax_rate": Decimal("25.0"),
            "days_to_start_business": 2,
            "total_exports": Decimal("14500.00"),
            "total_imports": Decimal("12000.00"),
            "key_industries": "Cocoa, Cashew, Oil Refining, Manufacturing, Construction, Banking",
            "trade_agreements": "ECOWAS, WAEMU, AfCFTA, EPA",
            "electricity_access": Decimal("70.0"),
            "internet_penetration": Decimal("58.0"),
            "paved_roads_percent": Decimal("8.0"),
            "number_of_airports": 28,
            "is_active": True,
            "featured": True,
            "display_order": 50,
        },
        {
            "country_name": "The Gambia",
            "country_code": "GM",
            "slug": "gambia",
            "ipa_full_name": "Gambia Investment and Export Promotion Agency",
            "ipa_acronym": "GIEPA",
            "tagline": "The Smiling Coast of Africa",
            "overview": "The Gambia is a small but strategically located country with population of 2.8 million and GDP of USD 2.6 billion. GIEPA promotes investment and exports, focusing on tourism, agriculture, and services. Despite its size, Gambia offers unique investment opportunities in niche sectors.",
            # "why_invest": "English-speaking, stable democracy, tourism potential, strategic location along Gambia River",
            "contact_email": "info@giepa.gm",
            "contact_phone": "+220 437 3232",
            "ipa_website": "https://www.giepa.gm",
            "physical_address": "Banjul, The Gambia",
            "capital_city": "Banjul",
            "official_language": "English",
            "currency_code": "GMD",
            "currency_symbol": "D",
            "time_zone": "GMT",
            "flag_emoji": "🇬🇲",
            "population": 2800000,
            "population_growth": Decimal("2.9"),
            "gdp": Decimal("2600000000"),
            "gdp_growth_rate": Decimal("5.3"),
            "gdp_per_capita": Decimal("930"),
            "inflation_rate": Decimal("11.5"),
            "median_age": Decimal("17.0"),
            "urbanization_rate": Decimal("63.0"),
            "literacy_rate": Decimal("55.0"),
            "ease_of_doing_business_rank": 155,
            "fdi_inflows": Decimal("85.00"),
            "corporate_tax_rate": Decimal("31.0"),
            "days_to_start_business": 27,
            "total_exports": Decimal("150.00"),
            "total_imports": Decimal("550.00"),
            "key_industries": "Tourism, Agriculture, Fisheries, Re-export Trade",
            "trade_agreements": "ECOWAS, AfCFTA, WTO",
            "electricity_access": Decimal("55.0"),
            "internet_penetration": Decimal("19.0"),
            "paved_roads_percent": Decimal("35.0"),
            "number_of_airports": 1,
            "is_active": True,
            "featured": False,
            "display_order": 60,
        },
    ]

    # Create member states
    for data in member_states_data:
        ms, created = MemberStateIPA.objects.get_or_create(slug=data["slug"], defaults=data)
        status = "✓ Created" if created else "- Exists"
        print(f"{status}: {ms.country_name} ({ms.ipa_acronym})")

    return MemberStateIPA.objects.all()


if __name__ == "__main__":
    member_states = create_member_states()

    print("\n" + "=" * 60)
    print("MEMBERS DATA POPULATION (Part 1) COMPLETE")
    print("=" * 60)
    print(f"\nCreated {member_states.count()} Member States")
    print("=" * 60)
