# Generated by Django 5.1 on 2025-11-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "organization",
                    models.CharField(blank=True, help_text="Organization/Company", max_length=200),
                ),
                ("job_title", models.CharField(blank=True, max_length=200)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "participant_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("investor", "Investor"),
                            ("ipa_staff", "IPA Staff"),
                            ("government", "Government Official"),
                            ("service_provider", "Service Provider"),
                            ("researcher", "Researcher/Academic"),
                            ("media", "Media"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("dietary_requirements", models.TextField(blank=True)),
                ("special_needs", models.TextField(blank=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, help_text="Payment transaction reference", max_length=100
                    ),
                ),
                (
                    "attended",
                    models.BooleanField(default=False, help_text="Did participant attend?"),
                ),
                (
                    "certificate_issued",
                    models.BooleanField(default=False, help_text="Was certificate issued?"),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Unique registration number", max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Partner organization name", max_length=200, unique=True
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("development", "Development Partner"),
                            ("international_org", "International Organization"),
                            ("private_sector", "Private Sector"),
                            ("research", "Research Institution"),
                            ("network", "Investment Network"),
                            ("government", "Government Agency"),
                            ("other", "Other"),
                        ],
                        help_text="Type of partner organization",
                        max_length=50,
                    ),
                ),
                (
                    "acronym",
                    models.CharField(
                        blank=True, help_text="Acronym (e.g., 'WAIPA', 'UNCTAD')", max_length=20
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Partner description and collaboration"),
                ),
                ("website", models.URLField(blank=True, help_text="Partner's official website")),
                (
                    "logo",
                    models.URLField(
                        blank=True, help_text="Partner logo URL (AWS S3)", max_length=500
                    ),
                ),
                (
                    "partnership_start_date",
                    models.DateField(blank=True, help_text="When partnership began", null=True),
                ),
                (
                    "partnership_areas",
                    models.TextField(blank=True, help_text="Areas of collaboration"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, help_text="Primary contact person", max_length=200
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Featured partner (show on homepage)"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Publication title", max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("annual_report", "Annual Report"),
                            ("investment_report", "Investment Report"),
                            ("policy_brief", "Policy Brief"),
                            ("research_paper", "Research Paper"),
                            ("guide", "Investment Guide"),
                            ("newsletter", "Newsletter"),
                            ("brochure", "Brochure"),
                            ("case_study", "Case Study"),
                            ("presentation", "Presentation"),
                            ("infographic", "Infographic"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Abstract or summary")),
                ("file", models.URLField(help_text="PDF or document URL (AWS S3)", max_length=500)),
                (
                    "file_size",
                    models.CharField(
                        blank=True, help_text="File size (e.g., '2.5 MB')", max_length=20
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, help_text="Author or organization", max_length=200
                    ),
                ),
                ("publication_date", models.DateField(help_text="Publication date")),
                ("year", models.IntegerField(help_text="Publication year")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("pt", "Portuguese")],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(
                        blank=True,
                        help_text="Cover image or thumbnail URL (AWS S3)",
                        max_length=500,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, help_text="Is publication published?"),
                ),
                ("featured", models.BooleanField(default=False, help_text="Featured publication?")),
                ("download_count", models.IntegerField(default=0, help_text="Number of downloads")),
                ("view_count", models.IntegerField(default=0, help_text="Number of views")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["-publication_date", "-featured"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Sector name (e.g., 'Agriculture & Agribusiness')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly version", max_length=100, unique=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Sector overview and importance"),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="CSS icon class (e.g., 'fas fa-tractor')",
                        max_length=100,
                    ),
                ),
                (
                    "icon_image",
                    models.URLField(
                        blank=True, help_text="Custom icon image URL (AWS S3)", max_length=500
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1B7A4C",
                        help_text="Brand color for this sector (hex code)",
                        max_length=20,
                    ),
                ),
                (
                    "market_overview",
                    models.TextField(blank=True, help_text="Market size and opportunity"),
                ),
                (
                    "regional_advantages",
                    models.TextField(blank=True, help_text="Why West Africa for this sector"),
                ),
                (
                    "investment_requirements",
                    models.TextField(blank=True, help_text="Typical investment requirements"),
                ),
                (
                    "hero_image",
                    models.URLField(
                        blank=True, help_text="Hero banner URL (AWS S3)", max_length=500
                    ),
                ),
                ("featured", models.BooleanField(default=False, help_text="Featured on homepage?")),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Display order (lower first)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this sector active?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectors",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Event title", max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("forum", "Investment Forum"),
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("training", "Training Program"),
                            ("webinar", "Webinar"),
                            ("mission", "Investment Mission"),
                            ("roadshow", "Roadshow"),
                            ("meeting", "Meeting"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(help_text="Event description")),
                ("start_date", models.DateField(help_text="Event start date")),
                ("end_date", models.DateField(help_text="Event end date")),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(default="GMT", help_text="Event timezone", max_length=50),
                ),
                (
                    "is_virtual",
                    models.BooleanField(default=False, help_text="Is this a virtual event?"),
                ),
                ("venue", models.CharField(blank=True, help_text="Venue name", max_length=300)),
                ("city", models.CharField(blank=True, help_text="City", max_length=100)),
                ("venue_address", models.TextField(blank=True)),
                ("virtual_link", models.URLField(blank=True, help_text="Virtual meeting link")),
                ("agenda", models.TextField(blank=True, help_text="Event agenda")),
                (
                    "target_audience",
                    models.JSONField(blank=True, default=list, help_text="Target audience groups"),
                ),
                (
                    "learning_objectives",
                    models.TextField(blank=True, help_text="What participants will learn"),
                ),
                ("speakers", models.TextField(blank=True, help_text="Speakers and facilitators")),
                (
                    "registration_required",
                    models.BooleanField(default=True, help_text="Is registration required?"),
                ),
                (
                    "registration_deadline",
                    models.DateField(blank=True, help_text="Registration deadline", null=True),
                ),
                (
                    "registration_link",
                    models.URLField(blank=True, help_text="External registration link"),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True, help_text="Maximum number of participants", null=True
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Registration fee in USD (0 for free)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "banner_image",
                    models.URLField(
                        blank=True, help_text="Event banner URL (AWS S3)", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("featured", models.BooleanField(default=False, help_text="Featured event?")),
                (
                    "event_report",
                    models.URLField(
                        blank=True, help_text="Post-event report URL (AWS S3)", max_length=500
                    ),
                ),
                (
                    "attendance_count",
                    models.IntegerField(blank=True, help_text="Number of attendees", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-start_date", "-featured"],
            },
        ),
    ]
