# Generated by Django 5.1 on 2025-11-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="host_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hosted_events",
                to="members.memberstateipa",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="core.event",
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["slug"], name="core_partne_slug_4e9d41_idx"),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["partner_type", "is_active"], name="core_partne_partner_3c214e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["featured", "display_order"], name="core_partne_feature_aa8a6b_idx"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizing_partners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Partners organizing the event",
                related_name="organized_events",
                to="core.partner",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="related_countries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related countries",
                related_name="publications",
                to="members.memberstateipa",
            ),
        ),
        migrations.AddIndex(
            model_name="sector",
            index=models.Index(fields=["slug"], name="core_sector_slug_432e4a_idx"),
        ),
        migrations.AddIndex(
            model_name="sector",
            index=models.Index(
                fields=["is_active", "featured"], name="core_sector_is_acti_fee309_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sector",
            index=models.Index(fields=["display_order"], name="core_sector_display_4e2821_idx"),
        ),
        migrations.AddField(
            model_name="publication",
            name="related_sectors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related sectors",
                related_name="publications",
                to="core.sector",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="related_sectors",
            field=models.ManyToManyField(blank=True, related_name="events", to="core.sector"),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "payment_status"], name="core_eventr_event_i_e6edfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["registration_number"], name="core_eventr_registr_13f7c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["-created_at"], name="core_eventr_created_97fc65_idx"),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["event", "attended"], name="core_eventr_event_i_783735_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "email")},
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["slug"], name="core_public_slug_d6a9ca_idx"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["publication_type", "published"], name="core_public_publica_3660d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["-publication_date"], name="core_public_publica_c53e26_idx"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["year", "published"], name="core_public_year_11398b_idx"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["featured", "-publication_date"], name="core_public_feature_be0fd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["slug"], name="core_event_slug_7e3734_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "status"], name="core_event_event_t_5dba9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["-start_date", "status"], name="core_event_start_d_4dfed5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["host_country", "status"], name="core_event_host_co_c5ac5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["featured", "-start_date"], name="core_event_feature_b2ecd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["registration_required", "status"], name="core_event_registr_0f5626_idx"
            ),
        ),
    ]
