# Generated by Django 5.1 on 2025-12-16 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("media_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="cover_media",
            field=models.ForeignKey(
                blank=True,
                help_text="Cover image from Media Library (overrides cover_image URL)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publication_covers",
                to="media_app.mediafile",
            ),
        ),
    ]
