# Generated by Django 5.1 on 2025-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_publication_cover_media"),
        ("knowledge_hub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="publications", to="knowledge_hub.tag"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="publications", to="knowledge_hub.topic"
            ),
        ),
    ]
