# Generated by Django 5.1 on 2025-11-30 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_ipauser_can_create_opportunities_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IPADashboardActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("password_change", "Password Changed"),
                            ("profile_update", "Profile Updated"),
                            ("profile_view", "Profile Viewed"),
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("publish", "Published"),
                            ("unpublish", "Unpublished"),
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("opportunity_create", "Opportunity Created"),
                            ("opportunity_update", "Opportunity Updated"),
                            ("opportunity_publish", "Opportunity Published"),
                            ("opportunity_delete", "Opportunity Deleted"),
                            ("inquiry_view", "Inquiry Viewed"),
                            ("inquiry_respond", "Inquiry Responded"),
                            ("inquiry_assign", "Inquiry Assigned"),
                            ("inquiry_close", "Inquiry Closed"),
                            ("user_invite", "User Invited"),
                            ("user_create", "User Created"),
                            ("user_update", "User Updated"),
                            ("user_deactivate", "User Deactivated"),
                            ("permission_change", "Permissions Changed"),
                            ("export_data", "Data Exported"),
                            ("export_report", "Report Exported"),
                            ("settings_change", "Settings Changed"),
                            ("bulk_import", "Bulk Import"),
                            ("bulk_update", "Bulk Update"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(help_text="Human-readable description of the action"),
                ),
                (
                    "changes_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON representation of before/after changes",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string from request"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When this activity occurred"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "member_state",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related member state",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_activities",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Activity",
                "verbose_name_plural": "Dashboard Activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"], name="dashboard_i_user_id_ba92cd_idx"
                    ),
                    models.Index(
                        fields=["member_state", "-timestamp"], name="dashboard_i_member__409ac7_idx"
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"], name="dashboard_i_action__5d9b3b_idx"
                    ),
                    models.Index(fields=["-timestamp"], name="dashboard_i_timesta_5d8491_idx"),
                    models.Index(
                        fields=["content_type", "object_id"], name="dashboard_i_content_978765_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IPANotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("inquiry", "New Investor Inquiry"),
                            ("inquiry_response", "Inquiry Response"),
                            ("approval_needed", "Approval Needed"),
                            ("approved", "Content Approved"),
                            ("rejected", "Content Rejected"),
                            ("opportunity_expiring", "Opportunity Expiring"),
                            ("team_member_added", "Team Member Added"),
                            ("team_member_removed", "Team Member Removed"),
                            ("permission_changed", "Your Permissions Changed"),
                            ("system_alert", "System Alert"),
                            ("announcement", "Announcement"),
                            ("reminder", "Reminder"),
                        ],
                        db_index=True,
                        help_text="Type of notification",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Short notification title", max_length=200)),
                ("message", models.TextField(help_text="Full notification message")),
                (
                    "link_url",
                    models.URLField(
                        blank=True, help_text="Optional link to relevant page", max_length=500
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Has notification been read?"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was read", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When notification was created"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="IPA user receiving this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.ipauser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"], name="dashboard_i_recipie_bdd253_idx"
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"], name="dashboard_i_recipie_f9a596_idx"
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="dashboard_i_notific_98e93f_idx",
                    ),
                ],
            },
        ),
    ]
