# Generated by Django 5.1 on 2026-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipadashboardactivity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("password_change", "Password Changed"),
                    ("profile_update", "Profile Updated"),
                    ("profile_view", "Profile Viewed"),
                    ("create", "Created"),
                    ("update", "Updated"),
                    ("delete", "Deleted"),
                    ("publish", "Published"),
                    ("unpublish", "Unpublished"),
                    ("approve", "Approved"),
                    ("reject", "Rejected"),
                    ("opportunity_create", "Opportunity Created"),
                    ("opportunity_update", "Opportunity Updated"),
                    ("opportunity_publish", "Opportunity Published"),
                    ("opportunity_delete", "Opportunity Deleted"),
                    ("inquiry_view", "Inquiry Viewed"),
                    ("inquiry_respond", "Inquiry Responded"),
                    ("inquiry_assign", "Inquiry Assigned"),
                    ("inquiry_close", "Inquiry Closed"),
                    ("user_invite", "User Invited"),
                    ("user_create", "User Created"),
                    ("user_update", "User Updated"),
                    ("user_deactivate", "User Deactivated"),
                    ("permission_change", "Permissions Changed"),
                    ("export_data", "Data Exported"),
                    ("export_report", "Report Exported"),
                    ("settings_change", "Settings Changed"),
                    ("bulk_import", "Bulk Import"),
                    ("bulk_update", "Bulk Update"),
                    ("bulk_invitation", "Bulk Invitation Sent"),
                    ("viewed_dashboard", "Dashboard Viewed"),
                    ("viewed_member_state_detail", "Member State Detail Viewed"),
                    ("viewed_user_detail", "User Detail Viewed"),
                    ("published_opportunity", "Opportunity Published (direct)"),
                    ("unpublished_opportunity", "Opportunity Unpublished"),
                    ("created_opportunity", "Opportunity Created as Draft"),
                    ("featured_opportunity", "Opportunity Featured"),
                    ("unfeatured_opportunity", "Opportunity Unfeatured"),
                    ("updated_user", "User Updated"),
                    ("updated_permissions", "Permissions Updated"),
                    ("activate_user", "User Activated"),
                    ("deactivate_user", "User Deactivated"),
                    ("reset_password_user", "User Password Reset"),
                    ("created_news", "News Article Created"),
                    ("updated_news", "News Article Updated"),
                    ("deleted_news", "News Article Deleted"),
                ],
                db_index=True,
                help_text="Type of action performed",
                max_length=50,
            ),
        ),
    ]
