# Generated by Django 5.1 on 2025-11-28 11:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPAUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ipa_admin", "IPA Administrator"),
                            ("ipa_editor", "IPA Editor"),
                            ("ipa_data_entry", "IPA Data Entry"),
                        ],
                        default="ipa_editor",
                        help_text="User's role within their IPA",
                        max_length=20,
                    ),
                ),
                (
                    "can_publish_opportunities",
                    models.BooleanField(
                        default=False, help_text="Can publish opportunities without approval?"
                    ),
                ),
                (
                    "can_approve_data",
                    models.BooleanField(
                        default=False, help_text="Can approve WAIIS data submissions?"
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False, help_text="Can create/edit other IPA users?"
                    ),
                ),
                (
                    "direct_phone",
                    models.CharField(
                        blank=True, help_text="Direct line phone number", max_length=50
                    ),
                ),
                (
                    "extension",
                    models.CharField(blank=True, help_text="Phone extension", max_length=20),
                ),
                (
                    "office_location",
                    models.CharField(
                        blank=True, help_text="Office location/building", max_length=200
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this IPA user account active?"),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(
                        default=False, help_text="Is this the primary focal point?"
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(default=False, help_text="Has user completed onboarding?"),
                ),
                (
                    "training_completed",
                    models.BooleanField(default=False, help_text="Has user completed training?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IPA User Profile",
                "verbose_name_plural": "IPA User Profiles",
                "ordering": ["member_state", "-is_primary_contact", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("ipa_staff", "IPA Staff"),
                            ("ipawas_admin", "IPAWAS Admin"),
                            ("public", "Public User"),
                        ],
                        default="public",
                        help_text="User type determines access level",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, help_text="Contact phone number", max_length=50),
                ),
                (
                    "job_title",
                    models.CharField(blank=True, help_text="Professional title", max_length=200),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, help_text="Organization/Company name", max_length=200
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, help_text="Has user verified their email?"),
                ),
                (
                    "email_verification_token",
                    models.CharField(
                        blank=True, help_text="Token for email verification", max_length=100
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(default=False, help_text="Is 2FA enabled for this user?"),
                ),
                (
                    "two_factor_secret",
                    models.CharField(blank=True, help_text="TOTP secret for 2FA", max_length=100),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of last login", null=True
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, help_text="Last activity timestamp", null=True
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("pt", "Portuguese")],
                        default="en",
                        help_text="Preferred interface language",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="UTC", help_text="User's timezone", max_length=50),
                ),
                (
                    "email_notifications",
                    models.BooleanField(default=True, help_text="Receive email notifications?"),
                ),
                (
                    "profile_picture",
                    models.URLField(
                        blank=True, help_text="Profile photo URL (AWS S3)", max_length=500
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="Short bio (optional)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
