# Generated by Django 5.1 on 2025-11-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipauser",
            name="member_state",
            field=models.ForeignKey(
                help_text="IPA this user belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ipa_users",
                to="members.memberstateipa",
            ),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="user",
            field=models.OneToOneField(
                help_text="Associated user account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ipa_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type", "is_active"], name="accounts_us_user_ty_029544_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["-date_joined"], name="accounts_us_date_jo_bab293_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email_verified"], name="accounts_us_email_v_054104_idx"),
        ),
        migrations.AddIndex(
            model_name="ipauser",
            index=models.Index(
                fields=["member_state", "is_active"], name="accounts_ip_member__26cf1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipauser",
            index=models.Index(fields=["role", "is_active"], name="accounts_ip_role_15e971_idx"),
        ),
        migrations.AddIndex(
            model_name="ipauser",
            index=models.Index(
                fields=["is_primary_contact"], name="accounts_ip_is_prim_c391d8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ipauser",
            unique_together={("user", "member_state")},
        ),
    ]
