# Generated by Django 5.1 on 2025-11-29 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipauser",
            name="can_create_opportunities",
            field=models.BooleanField(
                default=True, help_text="Can create investment opportunities?"
            ),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="can_edit_incentives",
            field=models.BooleanField(default=True, help_text="Can manage investment incentives?"),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="can_edit_profile",
            field=models.BooleanField(default=True, help_text="Can edit member state profile?"),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="can_export_data",
            field=models.BooleanField(default=False, help_text="Can export data and reports?"),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="can_manage_sectors",
            field=models.BooleanField(default=True, help_text="Can add/edit priority sectors?"),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="can_manage_success_stories",
            field=models.BooleanField(default=True, help_text="Can create/edit success stories?"),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="can_respond_to_inquiries",
            field=models.BooleanField(default=True, help_text="Can respond to investor inquiries?"),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="can_view_analytics",
            field=models.BooleanField(default=True, help_text="Can access analytics dashboard?"),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="can_view_inquiries",
            field=models.BooleanField(default=True, help_text="Can view investor inquiries?"),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="dashboard_access_granted_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When dashboard access was granted", null=True
            ),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="dashboard_onboarding_completed",
            field=models.BooleanField(
                default=False, help_text="Has user completed dashboard tour?"
            ),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="last_dashboard_login",
            field=models.DateTimeField(
                blank=True, help_text="Last time user accessed dashboard", null=True
            ),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="notify_on_inquiry",
            field=models.BooleanField(default=True, help_text="Notify when new inquiry received?"),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="notify_on_opportunity_expiry",
            field=models.BooleanField(
                default=True, help_text="Notify when opportunities are expiring?"
            ),
        ),
        migrations.AddField(
            model_name="ipauser",
            name="notify_on_team_changes",
            field=models.BooleanField(
                default=True, help_text="Notify when team members are added/removed?"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="accepted_invitation_at",
            field=models.DateTimeField(
                blank=True, help_text="When user accepted their invitation", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account_locked_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Account locked until this time (after failed attempts)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Counter for failed login attempts"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="invitation_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Token used for registration (if invited)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who sent the invitation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True, help_text="Last password change timestamp", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="ipauser",
            index=models.Index(
                fields=["-last_dashboard_login"], name="accounts_ip_last_da_7d1fdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["invitation_token"], name="accounts_us_invitat_4b7e5d_idx"),
        ),
    ]
