# Generated by Django 5.2.5 on 2026-04-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipauser',
            name='role',
            field=models.CharField(choices=[('ipa_director', 'IPA Director'), ('ipa_manager', 'IPA Manager'), ('ipa_officer', 'IPA Officer'), ('ipa_data_entry', 'IPA Data Entry'), ('ipa_analyst', 'IPA Analyst')], default='ipa_officer', help_text="User's role within their IPA", max_length=20),
        ),
    ]
