# Generated by Django 5.1 on 2025-12-16 15:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_publication_cover_media"),
        ("media_app", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="FontAwesome icon class (e.g., 'fa-chart-line')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#10B981", help_text="Hex color for UI display", max_length=7
                    ),
                ),
                (
                    "content_count",
                    models.IntegerField(
                        default=0, help_text="Cached count of content with this topic"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("press_event", "Press Event"),
                            ("leadership", "Leadership Photos"),
                            ("facilities", "Facilities"),
                            ("projects", "Project Photos"),
                            ("meetings", "Meetings & Conferences"),
                            ("branding", "Branding & Logos"),
                            ("promotional", "Promotional Videos"),
                            ("documentary", "Documentary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "is_public",
                    models.BooleanField(default=True, help_text="Show in public Media Center"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_files",
                    models.ManyToManyField(
                        help_text="Files from Media Library to display publicly",
                        related_name="public_categories",
                        to="media_app.mediafile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Category",
                "verbose_name_plural": "Media Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MediaKitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("logo_pack", "Logo Package"),
                            ("brand_guide", "Brand Guidelines"),
                            ("fact_sheet", "Fact Sheet"),
                            ("leadership_photos", "Leadership Photos"),
                            ("facility_photos", "Facility Photos"),
                            ("infographic", "Infographic"),
                            ("presentation", "Presentation Template"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional files in this package",
                        related_name="mediakit_additional",
                        to="media_app.mediafile",
                    ),
                ),
                (
                    "primary_file",
                    models.ForeignKey(
                        help_text="Main file for this media kit item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediakit_primary",
                        to="media_app.mediafile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Kit Item",
                "verbose_name_plural": "Media Kit Items",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("investment_guide", "Investment Guide"),
                            ("toolkit", "Toolkit"),
                            ("template", "Template"),
                            ("legal_document", "Legal Document"),
                            ("data_tool", "Data Tool"),
                            ("checklist", "Checklist"),
                            ("handbook", "Handbook"),
                            ("form", "Form"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="e.g., 'v2.0', '2024 Edition'", max_length=50
                    ),
                ),
                ("last_updated", models.DateField(db_index=True)),
                ("published", models.BooleanField(db_index=True, default=True)),
                ("featured", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_countries",
                    models.ManyToManyField(
                        blank=True, related_name="resources", to="members.memberstateipa"
                    ),
                ),
                (
                    "related_sectors",
                    models.ManyToManyField(blank=True, related_name="resources", to="core.sector"),
                ),
                (
                    "resource_file",
                    models.ForeignKey(
                        help_text="Resource file from Media Library",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="media_app.mediafile",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="resources", to="knowledge_hub.tag"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="resources", to="knowledge_hub.topic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "ordering": ["-last_updated", "-featured"],
                "indexes": [
                    models.Index(fields=["slug"], name="knowledge_h_slug_529ed6_idx"),
                    models.Index(
                        fields=["resource_type", "published"], name="knowledge_h_resourc_fd2056_idx"
                    ),
                    models.Index(fields=["-last_updated"], name="knowledge_h_last_up_7f863d_idx"),
                    models.Index(
                        fields=["featured", "-last_updated"], name="knowledge_h_feature_b140cc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PressRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("summary", models.TextField(max_length=500)),
                ("content", models.TextField(help_text="Full press release content")),
                ("release_date", models.DateField(db_index=True)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="e.g., 'Abuja, Nigeria'", max_length=200
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("published", models.BooleanField(db_index=True, default=True)),
                ("view_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="press_releases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media_assets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Photos/videos from the press event",
                        related_name="related_press_releases",
                        to="media_app.mediafile",
                    ),
                ),
                (
                    "pdf_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="PDF version from Media Library",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="press_releases",
                        to="media_app.mediafile",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="press_releases", to="knowledge_hub.tag"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="press_releases", to="knowledge_hub.topic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Press Release",
                "verbose_name_plural": "Press Releases",
                "ordering": ["-release_date"],
                "indexes": [
                    models.Index(fields=["slug"], name="knowledge_h_slug_a4187b_idx"),
                    models.Index(
                        fields=["-release_date", "published"], name="knowledge_h_release_4790e7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("investment_news", "Investment News"),
                            ("regional_updates", "Regional Updates"),
                            ("success_stories", "Success Stories"),
                            ("policy_updates", "Policy Updates"),
                            ("blog", "Blog"),
                            ("event_coverage", "Event Coverage"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(help_text="Brief summary for previews", max_length=500),
                ),
                ("content", models.TextField(help_text="Full article content (HTML supported)")),
                ("author", models.CharField(max_length=200)),
                ("author_title", models.CharField(blank=True, max_length=200)),
                ("publication_date", models.DateTimeField(db_index=True)),
                (
                    "reading_time",
                    models.IntegerField(default=5, help_text="Estimated reading time in minutes"),
                ),
                ("view_count", models.IntegerField(default=0)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
                ),
                ("published", models.BooleanField(db_index=True, default=True)),
                ("featured", models.BooleanField(default=False, help_text="Show as featured news")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_articles_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "featured_media",
                    models.ForeignKey(
                        blank=True,
                        help_text="Featured image from Media Library",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_in_articles",
                        to="media_app.mediafile",
                    ),
                ),
                (
                    "related_countries",
                    models.ManyToManyField(
                        blank=True, related_name="news_articles", to="members.memberstateipa"
                    ),
                ),
                (
                    "related_sectors",
                    models.ManyToManyField(
                        blank=True, related_name="news_articles", to="core.sector"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="news_articles", to="knowledge_hub.tag"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="news_articles", to="knowledge_hub.topic"
                    ),
                ),
            ],
            options={
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
                "ordering": ["-publication_date", "-featured"],
                "indexes": [
                    models.Index(fields=["slug"], name="knowledge_h_slug_3156d9_idx"),
                    models.Index(
                        fields=["category", "published"], name="knowledge_h_categor_a1ebb9_idx"
                    ),
                    models.Index(
                        fields=["-publication_date"], name="knowledge_h_publica_e36ff6_idx"
                    ),
                    models.Index(
                        fields=["featured", "-publication_date"],
                        name="knowledge_h_feature_f6ecce_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="knowledge_h_search__878f15_gin"
                    ),
                ],
            },
        ),
    ]
