# Generated by Django 5.1 on 2025-12-22 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_publication_tags_publication_topics"),
        ("knowledge_hub", "0001_initial"),
        ("media_app", "0001_initial"),
        ("members", "0002_memberstateipa_corporate_tax_rate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="content_blocks",
            field=models.JSONField(
                default=list,
                help_text="Structured content: [{type: 'paragraph', content: '...'}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="member_state",
            field=models.ForeignKey(
                blank=True,
                help_text="If NULL, this is HQ/platform-wide news",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_articles",
                to="members.memberstateipa",
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="scope",
            field=models.CharField(
                choices=[("hq", "HQ/Platform-wide"), ("country", "Country-specific")],
                db_index=True,
                default="hq",
                help_text="Determines visibility scope",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="supporting_images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional images shown in article carousel",
                related_name="news_article_gallery",
                to="media_app.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="content",
            field=models.TextField(blank=True, help_text="Full article content (HTML supported)"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="excerpt",
            field=models.TextField(
                help_text="Brief summary for previews and meta descriptions", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="featured_media",
            field=models.ForeignKey(
                blank=True,
                help_text="Main hero image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_in_articles",
                to="media_app.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="related_countries",
            field=models.ManyToManyField(
                blank=True, related_name="related_news_articles", to="members.memberstateipa"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["member_state", "published"], name="knowledge_h_member__710792_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(fields=["scope", "published"], name="knowledge_h_scope_a53a7b_idx"),
        ),
    ]
