# Generated by Django 5.1 on 2025-11-28 11:07

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaiisDataSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        help_text="Unique submission ID (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[("annual", "Annual Data"), ("quarterly", "Quarterly Data")],
                        default="annual",
                        help_text="Annual or quarterly data",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Data year",
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "quarter",
                    models.IntegerField(
                        blank=True,
                        help_text="Quarter (1-4) if quarterly data",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "fdi_inflow",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="FDI Inflow (USD millions)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "fdi_outflow",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="FDI Outflow (USD millions)",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "fdi_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total FDI Stock (USD millions)",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "number_of_projects",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of FDI projects",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "greenfield_projects",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of greenfield projects",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "expansion_projects",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of expansion projects",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "jobs_created",
                    models.IntegerField(
                        blank=True,
                        help_text="Jobs created by FDI",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "jobs_sustained",
                    models.IntegerField(
                        blank=True,
                        help_text="Jobs sustained by FDI",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gdp_contribution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated GDP contribution (USD millions)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "tax_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tax revenue from FDI (USD millions)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        help_text="Primary data source (e.g., 'Central Bank of Nigeria')",
                        max_length=300,
                    ),
                ),
                (
                    "secondary_sources",
                    models.TextField(blank=True, help_text="Additional data sources"),
                ),
                (
                    "methodology_notes",
                    models.TextField(blank=True, help_text="Data collection methodology"),
                ),
                (
                    "data_quality_notes",
                    models.TextField(blank=True, help_text="Notes on data quality or limitations"),
                ),
                (
                    "supporting_document",
                    models.URLField(
                        blank=True,
                        help_text="Supporting documentation URL (PDF, Excel) (AWS S3)",
                        max_length=500,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for Review"),
                            ("under_review", "Under Review"),
                            ("revision_requested", "Revision Requested"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Current validation status",
                        max_length=30,
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        blank=True, help_text="When data was submitted for review", null=True
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateTimeField(blank=True, help_text="When data was reviewed", null=True),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Reviewer's notes or feedback"),
                ),
                (
                    "revision_notes",
                    models.TextField(blank=True, help_text="Notes for revision if requested"),
                ),
                (
                    "approved_date",
                    models.DateTimeField(blank=True, help_text="When data was approved", null=True),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, help_text="When data was published", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved publication",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waiis_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_state",
                    models.ForeignKey(
                        help_text="Country submitting data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiis_submissions",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="IPAWAS admin who reviewed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waiis_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="IPA user who submitted data",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waiis_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WAIIS Data Submission",
                "verbose_name_plural": "WAIIS Data Submissions",
                "ordering": ["-year", "-quarter", "member_state"],
            },
        ),
        migrations.CreateModel(
            name="WaiisDataAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("submitted", "Submitted for Review"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                            ("deleted", "Deleted"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        help_text="Type of action performed",
                        max_length=30,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, help_text="JSON of what changed", null=True),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of user", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="When action occurred"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        help_text="User who performed action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_trail",
                        to="waiis.waiisdatasubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "WAIIS Data Audit Log",
                "verbose_name_plural": "WAIIS Data Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WaiisSectorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fdi_inflow",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="FDI Inflow for this sector (USD millions)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "number_of_projects",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of projects in this sector",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "jobs_created",
                    models.IntegerField(
                        blank=True,
                        help_text="Jobs created in this sector",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "percentage_of_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of total FDI",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "sector",
                    models.ForeignKey(
                        help_text="Investment sector",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waiis_data",
                        to="core.sector",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Parent submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_data",
                        to="waiis.waiisdatasubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "WAIIS Sector Data",
                "verbose_name_plural": "WAIIS Sector Data",
                "ordering": ["submission", "-fdi_inflow"],
            },
        ),
        migrations.CreateModel(
            name="WaiisSourceCountryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_country_name",
                    models.CharField(help_text="Country of origin for FDI", max_length=100),
                ),
                (
                    "source_country_code",
                    models.CharField(blank=True, help_text="ISO country code", max_length=3),
                ),
                (
                    "fdi_inflow",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="FDI from this country (USD millions)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "number_of_projects",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of projects from this country",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "percentage_of_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of total FDI",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Parent submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_country_data",
                        to="waiis.waiisdatasubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "WAIIS Source Country Data",
                "verbose_name_plural": "WAIIS Source Country Data",
                "ordering": ["submission", "-fdi_inflow"],
            },
        ),
        migrations.CreateModel(
            name="WaiisAnalyticsCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cache_type",
                    models.CharField(
                        choices=[
                            ("regional_total", "Regional Total"),
                            ("country_comparison", "Country Comparison"),
                            ("sector_breakdown", "Sector Breakdown"),
                            ("source_country_analysis", "Source Country Analysis"),
                            ("time_series", "Time Series Data"),
                            ("top_performers", "Top Performing Countries"),
                            ("growth_rates", "Growth Rates"),
                        ],
                        help_text="Type of cached data",
                        max_length=50,
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        help_text="Unique cache identifier", max_length=200, unique=True
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, help_text="Data year (if applicable)", null=True
                    ),
                ),
                ("cached_data", models.JSONField(help_text="Cached analytical data")),
                ("expires_at", models.DateTimeField(help_text="When cache expires")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member_state",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific country (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_cache",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific sector (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_cache",
                        to="core.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "WAIIS Analytics Cache",
                "verbose_name_plural": "WAIIS Analytics Caches",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["cache_type", "year"], name="waiis_waiis_cache_t_eb0488_idx"
                    ),
                    models.Index(fields=["expires_at"], name="waiis_waiis_expires_9cdfaf_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WaiisDataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        help_text="What was exported (e.g., 'regional_fdi', 'country_data')",
                        max_length=50,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("pdf", "PDF"),
                            ("json", "JSON"),
                        ],
                        help_text="Export file format",
                        max_length=20,
                    ),
                ),
                (
                    "filters_applied",
                    models.JSONField(
                        blank=True,
                        help_text="Filters used (year, country, sector, etc.)",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "file_generated",
                    models.URLField(
                        blank=True,
                        help_text="Generated export file URL (optional storage) (AWS S3)",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who exported (if logged in)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waiis_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WAIIS Data Export",
                "verbose_name_plural": "WAIIS Data Exports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="waiis_waiis_created_853ce2_idx"),
                    models.Index(
                        fields=["user", "-created_at"], name="waiis_waiis_user_id_f2fb04_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="waiisdatasubmission",
            index=models.Index(
                fields=["member_state", "year", "quarter"], name="waiis_waiis_member__f3010a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waiisdatasubmission",
            index=models.Index(
                fields=["validation_status", "-submitted_date"],
                name="waiis_waiis_validat_5e7f07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="waiisdatasubmission",
            index=models.Index(fields=["year", "data_type"], name="waiis_waiis_year_277d70_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="waiisdatasubmission",
            unique_together={("member_state", "year", "quarter", "data_type")},
        ),
        migrations.AddIndex(
            model_name="waiisdataaudit",
            index=models.Index(
                fields=["submission", "-timestamp"], name="waiis_waiis_submiss_fd22d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waiisdataaudit",
            index=models.Index(
                fields=["performed_by", "-timestamp"], name="waiis_waiis_perform_bc2b06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waiissectordata",
            index=models.Index(
                fields=["submission", "sector"], name="waiis_waiis_submiss_15166d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waiissectordata",
            index=models.Index(
                fields=["sector", "-fdi_inflow"], name="waiis_waiis_sector__9934fd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="waiissectordata",
            unique_together={("submission", "sector")},
        ),
        migrations.AddIndex(
            model_name="waiissourcecountrydata",
            index=models.Index(
                fields=["submission", "source_country_name"], name="waiis_waiis_submiss_65bf1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waiissourcecountrydata",
            index=models.Index(
                fields=["source_country_name", "-fdi_inflow"], name="waiis_waiis_source__030d99_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="waiissourcecountrydata",
            unique_together={("submission", "source_country_name")},
        ),
    ]
