# Generated by Django 5.1 on 2025-11-28 11:07

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Opportunity title", max_length=300)),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly version", max_length=300, unique=True),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Unique reference (e.g., OPP-NGA-2025-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Brief summary (2-3 sentences, 200 chars max)", max_length=500
                    ),
                ),
                ("description", models.TextField(help_text="Detailed project description")),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("greenfield", "Greenfield Project"),
                            ("brownfield", "Brownfield Project"),
                            ("ppp", "Public-Private Partnership"),
                            ("privatization", "Privatization"),
                            ("joint_venture", "Joint Venture"),
                            ("expansion", "Expansion Opportunity"),
                            ("acquisition", "Acquisition"),
                            ("concession", "Concession"),
                        ],
                        help_text="Type of investment opportunity",
                        max_length=50,
                    ),
                ),
                (
                    "sub_sector",
                    models.CharField(
                        blank=True, help_text="Specific sub-sector or industry", max_length=200
                    ),
                ),
                (
                    "is_regional",
                    models.BooleanField(
                        default=False, help_text="Is this a regional/multi-country opportunity?"
                    ),
                ),
                (
                    "specific_location",
                    models.CharField(
                        blank=True, help_text="Specific city, state, or region", max_length=300
                    ),
                ),
                (
                    "geographic_coordinates",
                    models.JSONField(
                        blank=True,
                        help_text="Lat/Long for mapping (e.g., {'lat': 9.0765, 'lng': 7.3986})",
                        null=True,
                    ),
                ),
                (
                    "investment_required_min",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum investment required (USD)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "investment_required_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum investment (USD) - optional",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "investment_breakdown",
                    models.JSONField(
                        blank=True,
                        help_text="Cost breakdown (e.g., {'land': 1000000, 'equipment': 5000000})",
                        null=True,
                    ),
                ),
                (
                    "expected_roi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected ROI percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("999.99")),
                        ],
                    ),
                ),
                (
                    "payback_period",
                    models.CharField(
                        blank=True,
                        help_text="Expected payback period (e.g., '3-5 years')",
                        max_length=100,
                    ),
                ),
                (
                    "project_stage",
                    models.CharField(
                        choices=[
                            ("concept", "Concept Stage"),
                            ("feasibility", "Feasibility Study Complete"),
                            ("ready", "Investment Ready"),
                            ("partial", "Partially Funded"),
                            ("negotiation", "Under Negotiation"),
                        ],
                        default="concept",
                        help_text="Current stage of project development",
                        max_length=50,
                    ),
                ),
                (
                    "implementation_timeline",
                    models.CharField(
                        blank=True,
                        help_text="Expected timeline (e.g., '18-24 months')",
                        max_length=200,
                    ),
                ),
                (
                    "start_date_target",
                    models.DateField(blank=True, help_text="Target start date", null=True),
                ),
                (
                    "implementing_agency",
                    models.CharField(
                        blank=True,
                        help_text="Government agency or organization implementing",
                        max_length=300,
                    ),
                ),
                (
                    "implementing_agency_contact",
                    models.CharField(
                        blank=True,
                        help_text="Contact person at implementing agency",
                        max_length=300,
                    ),
                ),
                (
                    "investor_profile",
                    models.TextField(
                        blank=True, help_text="Desired investor profile and qualifications"
                    ),
                ),
                (
                    "technical_requirements",
                    models.TextField(
                        blank=True, help_text="Technical capabilities or expertise required"
                    ),
                ),
                (
                    "minimum_equity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum equity required (USD)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "local_content_requirements",
                    models.TextField(
                        blank=True, help_text="Local content or local partnership requirements"
                    ),
                ),
                (
                    "market_analysis",
                    models.TextField(blank=True, help_text="Market opportunity and analysis"),
                ),
                (
                    "target_market",
                    models.CharField(
                        blank=True,
                        help_text="Target market (e.g., 'Regional - ECOWAS', 'Global')",
                        max_length=300,
                    ),
                ),
                (
                    "revenue_projections",
                    models.TextField(blank=True, help_text="Expected revenue projections"),
                ),
                (
                    "financial_incentives_available",
                    models.TextField(
                        blank=True, help_text="Tax incentives and financial support available"
                    ),
                ),
                (
                    "regulatory_framework",
                    models.TextField(blank=True, help_text="Relevant laws and regulations"),
                ),
                (
                    "approval_process",
                    models.TextField(blank=True, help_text="Steps to get project approved"),
                ),
                (
                    "licenses_required",
                    models.TextField(blank=True, help_text="Required licenses and permits"),
                ),
                (
                    "land_availability",
                    models.TextField(
                        blank=True, help_text="Land availability and acquisition process"
                    ),
                ),
                (
                    "risk_factors",
                    models.TextField(blank=True, help_text="Key risk factors to consider"),
                ),
                (
                    "mitigation_measures",
                    models.TextField(blank=True, help_text="Risk mitigation strategies in place"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("active", "Active"),
                            ("negotiation", "Under Negotiation"),
                            ("funded", "Funded/Closed"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Publication status",
                        max_length=20,
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("high", "High Priority"),
                            ("medium", "Medium Priority"),
                            ("standard", "Standard"),
                        ],
                        default="standard",
                        help_text="Priority level for marketing",
                        max_length=20,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, help_text="Is this opportunity published?"),
                ),
                (
                    "published_date",
                    models.DateTimeField(blank=True, help_text="Date when published", null=True),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Featured opportunity (homepage, etc.)"
                    ),
                ),
                (
                    "thumbnail_image",
                    models.URLField(
                        blank=True,
                        help_text="Thumbnail URL for cards (400x250) (AWS S3)",
                        max_length=500,
                    ),
                ),
                (
                    "hero_image",
                    models.URLField(
                        blank=True, help_text="Hero banner URL (1920x1080) (AWS S3)", max_length=500
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image URLs for gallery"
                    ),
                ),
                ("video_url", models.URLField(blank=True, help_text="YouTube or Vimeo video URL")),
                ("views_count", models.IntegerField(default=0, help_text="Number of views")),
                (
                    "inquiries_count",
                    models.IntegerField(default=0, help_text="Number of inquiries received"),
                ),
                (
                    "downloads_count",
                    models.IntegerField(default=0, help_text="Number of document downloads"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_date",
                    models.DateTimeField(blank=True, help_text="Date when approved", null=True),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved publication",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this opportunity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participating_countries",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Countries involved (if regional)",
                        related_name="regional_opportunities",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "primary_country",
                    models.ForeignKey(
                        help_text="Primary country for this opportunity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "primary_sector",
                    models.ForeignKey(
                        help_text="Main sector for this opportunity",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_opportunities",
                        to="core.sector",
                    ),
                ),
                (
                    "secondary_sectors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional relevant sectors",
                        related_name="secondary_opportunities",
                        to="core.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investment Opportunity",
                "verbose_name_plural": "Investment Opportunities",
                "ordering": ["-featured", "-priority_level", "-published_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Document title", max_length=300)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("feasibility", "Feasibility Study"),
                            ("business_plan", "Business Plan"),
                            ("technical", "Technical Specifications"),
                            ("financial", "Financial Projections"),
                            ("legal", "Legal Documents"),
                            ("environmental", "Environmental Assessment"),
                            ("market_study", "Market Study"),
                            ("presentation", "Presentation"),
                            ("brochure", "Brochure"),
                            ("other", "Other"),
                        ],
                        help_text="Type of document",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.URLField(
                        help_text="Document URL (PDF, Word, Excel, etc.) (AWS S3)", max_length=500
                    ),
                ),
                (
                    "file_size",
                    models.CharField(
                        blank=True, help_text="File size (auto-calculated)", max_length=20
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Brief description of document"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Publicly downloadable? (False = requires login/approval)",
                    ),
                ),
                (
                    "requires_nda",
                    models.BooleanField(
                        default=False, help_text="Does this require NDA to access?"
                    ),
                ),
                ("download_count", models.IntegerField(default=0, help_text="Number of downloads")),
                ("display_order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="opportunities.investmentopportunity",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Document",
                "verbose_name_plural": "Opportunity Documents",
                "ordering": ["opportunity", "display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Unique inquiry reference", max_length=50, unique=True
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Investor/representative name", max_length=200),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "company_name",
                    models.CharField(
                        blank=True, help_text="Company/Organization name", max_length=200
                    ),
                ),
                (
                    "company_country",
                    models.CharField(
                        blank=True, help_text="Country where company is based", max_length=100
                    ),
                ),
                ("company_website", models.URLField(blank=True)),
                (
                    "investment_capacity",
                    models.CharField(
                        blank=True, help_text="Investment capacity range", max_length=100
                    ),
                ),
                (
                    "investment_timeline",
                    models.CharField(
                        blank=True, help_text="Expected investment timeline", max_length=100
                    ),
                ),
                (
                    "partnership_interest",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_ownership", "Full Ownership"),
                            ("majority", "Majority Stake"),
                            ("minority", "Minority Stake"),
                            ("joint_venture", "Joint Venture"),
                            ("other", "Other"),
                        ],
                        help_text="Ownership/partnership preference",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(help_text="Investor's message/inquiry")),
                (
                    "specific_questions",
                    models.TextField(
                        blank=True, help_text="Specific questions about the opportunity"
                    ),
                ),
                (
                    "experience_in_sector",
                    models.TextField(blank=True, help_text="Relevant experience in this sector"),
                ),
                (
                    "previous_investments",
                    models.TextField(blank=True, help_text="Previous investments in region/sector"),
                ),
                (
                    "requires_site_visit",
                    models.BooleanField(
                        default=False, help_text="Does investor want to schedule site visit?"
                    ),
                ),
                (
                    "requires_nda",
                    models.BooleanField(
                        default=False, help_text="Does investor require NDA before sharing details?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("disqualified", "Disqualified"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        help_text="Inquiry processing status",
                        max_length=20,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not visible to investor)"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(blank=True, help_text="Scheduled follow-up date", null=True),
                ),
                (
                    "investor_contacted_date",
                    models.DateTimeField(
                        blank=True, help_text="When investor was first contacted", null=True
                    ),
                ),
                (
                    "last_contact_date",
                    models.DateTimeField(
                        blank=True, help_text="Last communication date", null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="IPA staff handling this inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_opportunity_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="opportunities.investmentopportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Inquiry",
                "verbose_name_plural": "Opportunity Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("milestone", "Milestone Achieved"),
                            ("funding", "Funding Update"),
                            ("partnership", "Partnership Announcement"),
                            ("progress", "General Progress"),
                            ("other", "Other"),
                        ],
                        help_text="Type of update",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Update title", max_length=300)),
                ("description", models.TextField(help_text="Detailed update description")),
                ("is_public", models.BooleanField(default=True, help_text="Visible to public?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_updates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="opportunities.investmentopportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Update",
                "verbose_name_plural": "Opportunity Updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="investmentopportunity",
            index=models.Index(
                fields=["status", "published"], name="opportuniti_status_1599b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentopportunity",
            index=models.Index(
                fields=["primary_country", "status"], name="opportuniti_primary_2ec16d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentopportunity",
            index=models.Index(
                fields=["primary_sector", "status"], name="opportuniti_primary_21291e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentopportunity",
            index=models.Index(
                fields=["-featured", "-priority_level"], name="opportuniti_feature_1e1923_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitydocument",
            index=models.Index(
                fields=["opportunity", "document_type"], name="opportuniti_opportu_326190_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitydocument",
            index=models.Index(
                fields=["document_type", "is_public"], name="opportuniti_documen_1a5050_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitydocument",
            index=models.Index(
                fields=["opportunity", "display_order"], name="opportuniti_opportu_c63c85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityinquiry",
            index=models.Index(
                fields=["opportunity", "status"], name="opportuniti_opportu_594d6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityinquiry",
            index=models.Index(
                fields=["status", "-created_at"], name="opportuniti_status_198124_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityupdate",
            index=models.Index(
                fields=["opportunity", "-created_at"], name="opportuniti_opportu_8b151f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityupdate",
            index=models.Index(
                fields=["update_type", "is_public"], name="opportuniti_update__15eac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityupdate",
            index=models.Index(
                fields=["opportunity", "is_public"], name="opportuniti_opportu_1dd4af_idx"
            ),
        ),
    ]
