# Generated by Django 5.2.5 on 2026-05-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentopportunity',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('active', 'Published / Active'), ('negotiation', 'Under Negotiation'), ('funded', 'Funded / Closed'), ('suspended', 'Archived'), ('cancelled', 'Cancelled')], default='draft', help_text='Publication status', max_length=20),
        ),
    ]
