# Generated by Django 5.1 on 2026-05-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
        ('opportunities', '0002_alter_opportunity_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentopportunity',
            name='hero_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_heroes', to='media_app.mediafile'),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='thumbnail_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_thumbnails', to='media_app.mediafile'),
        ),
    ]
