# Generated by Django 5.1 on 2026-05-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_add_media_fk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentopportunity',
            name='factsheet_url',
            field=models.URLField(blank=True, help_text='Public link to the opportunity factsheet (Google Drive, Dropbox, S3, etc.)'),
        ),
    ]
