# Generated by Django 5.1 on 2025-11-30 18:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address of person being invited",
                        max_length=255,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for invitation link",
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ipa_admin", "IPA Administrator"),
                            ("ipa_editor", "IPA Editor"),
                            ("ipa_data_entry", "IPA Data Entry"),
                        ],
                        help_text="Role the invitee will have",
                        max_length=20,
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When invitation was created"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, help_text="When invitation expires"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of invitation",
                        max_length=20,
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="When invitation was accepted", null=True
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="When invitation was revoked", null=True
                    ),
                ),
                (
                    "revoke_reason",
                    models.TextField(blank=True, help_text="Reason for revoking invitation"),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(
                        default=False, help_text="Is this person the primary IPA contact?"
                    ),
                ),
                (
                    "invitation_message",
                    models.TextField(
                        blank=True, help_text="Optional personalized message to include in email"
                    ),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When invitation email was sent", null=True
                    ),
                ),
                (
                    "email_opened_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When invitation email was opened (if tracking enabled)",
                        null=True,
                    ),
                ),
                (
                    "registration_started_at",
                    models.DateTimeField(
                        blank=True, help_text="When recipient started registration", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User account created from this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_used",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who sent this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_state",
                    models.ForeignKey(
                        help_text="Member State IPA this invitation is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who revoked this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
                "ordering": ["-invited_at"],
                "indexes": [
                    models.Index(fields=["email", "status"], name="invitations_email_fc8d45_idx"),
                    models.Index(fields=["token"], name="invitations_token_3df640_idx"),
                    models.Index(
                        fields=["member_state", "status"], name="invitations_member__40723d_idx"
                    ),
                    models.Index(
                        fields=["status", "expires_at"], name="invitations_status_0460ba_idx"
                    ),
                    models.Index(fields=["-invited_at"], name="invitations_invited_d2205f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("email", "member_state"),
                        name="unique_pending_invitation_per_email_state",
                    )
                ],
            },
        ),
    ]
