# Generated by Django 5.2.5 on 2026-04-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('ipa_director', 'IPA Director'), ('ipa_manager', 'IPA Manager'), ('ipa_officer', 'IPA Officer'), ('ipa_data_entry', 'IPA Data Entry'), ('ipa_analyst', 'IPA Analyst')], help_text='Role the invitee will have', max_length=20),
        ),
    ]
