# Generated by Django 5.1 on 2026-05-11 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_expand_invitation_roles_to_five'),
        ('members', '0006_add_email_index_to_investor_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='unique_pending_invitation_per_email_state',
        ),
        migrations.AddField(
            model_name='invitation',
            name='user_type',
            field=models.CharField(choices=[('ipa_staff', 'IPA Staff'), ('ipawas_admin', 'IPAWAS HQ Admin')], default='ipa_staff', help_text='Type of user account to create on registration', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='member_state',
            field=models.ForeignKey(blank=True, help_text='Member State IPA this invitation is for (null for HQ admin invitations)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='members.memberstateipa'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(blank=True, choices=[('ipa_director', 'IPA Director'), ('ipa_manager', 'IPA Manager'), ('ipa_officer', 'IPA Officer'), ('ipa_data_entry', 'IPA Data Entry'), ('ipa_analyst', 'IPA Analyst')], help_text='Role the invitee will have (blank for HQ admin invitations)', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('member_state__isnull', False), ('status', 'pending')), fields=('email', 'member_state'), name='unique_pending_invitation_per_email_state'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('member_state__isnull', True), ('status', 'pending')), fields=('email',), name='unique_pending_hq_invitation_per_email'),
        ),
    ]
