# Generated by Django 5.1 on 2025-12-13 10:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Folder name (e.g., 'Annual Reports', 'Project Photos')",
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                (
                    "level",
                    models.IntegerField(
                        default=0,
                        help_text="Depth in hierarchy (0=root, 1=system, 2-3=custom)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "folder_type",
                    models.CharField(
                        choices=[
                            ("root", "Root Folder"),
                            ("documents", "Documents"),
                            ("images", "Images"),
                            ("videos", "Videos"),
                            ("others", "Others"),
                            ("custom", "Custom Folder"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System folders cannot be deleted or renamed"
                    ),
                ),
                (
                    "cloudinary_folder",
                    models.CharField(
                        blank=True,
                        help_text="Full path in Cloudinary (e.g., 'ipawas/nigeria/documents')",
                        max_length=500,
                    ),
                ),
                (
                    "full_path",
                    models.CharField(
                        blank=True, help_text="Computed full path for display", max_length=500
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_folders",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="media_app.mediafolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Folder",
                "verbose_name_plural": "Media Folders",
                "ordering": ["member_state", "level", "folder_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Display name for the file", max_length=255)),
                (
                    "original_filename",
                    models.CharField(help_text="Original uploaded filename", max_length=255),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "cloudinary_public_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier in Cloudinary",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "cloudinary_resource_type",
                    models.CharField(
                        help_text="Cloudinary resource type (image, video, raw)", max_length=20
                    ),
                ),
                (
                    "cloudinary_url",
                    models.URLField(help_text="Primary Cloudinary URL", max_length=1000),
                ),
                (
                    "cloudinary_secure_url",
                    models.URLField(help_text="HTTPS Cloudinary URL", max_length=1000),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, help_text="200px width thumbnail (images only)", max_length=1000
                    ),
                ),
                (
                    "medium_url",
                    models.URLField(
                        blank=True,
                        help_text="800px width medium size (images only)",
                        max_length=1000,
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, help_text="Width in pixels (images/videos)", null=True
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, help_text="Height in pixels (images/videos)", null=True
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds (videos/audio)", null=True
                    ),
                ),
                (
                    "is_optimized",
                    models.BooleanField(
                        default=False, help_text="Whether optimized versions have been generated"
                    ),
                ),
                (
                    "optimization_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional file metadata"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, help_text="Alt text for images (SEO)", max_length=255
                    ),
                ),
                ("caption", models.TextField(blank=True, help_text="File caption or description")),
                ("tags", models.JSONField(blank=True, default=list, help_text="Search tags")),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_state",
                    models.ForeignKey(
                        help_text="Denormalized for performance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="media_app.mediafolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(
                fields=["member_state", "parent"], name="media_app_m_member__b019bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(
                fields=["member_state", "is_system"], name="media_app_m_member__8738b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(
                fields=["member_state", "is_deleted"], name="media_app_m_member__a59119_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(
                fields=["level", "folder_type"], name="media_app_m_level_561940_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(fields=["cloudinary_folder"], name="media_app_m_cloudin_20238a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="mediafolder",
            unique_together={("member_state", "parent", "slug")},
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["member_state", "folder"], name="media_app_m_member__b70ef4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["member_state", "file_type"], name="media_app_m_member__556285_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["file_type", "member_state"], name="media_app_m_file_ty_9d74d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(fields=["-uploaded_at"], name="media_app_m_uploade_f6f0a7_idx"),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["uploaded_by", "-uploaded_at"], name="media_app_m_uploade_63fb9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["member_state", "is_deleted", "-uploaded_at"],
                name="media_app_m_member__bfe91e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["cloudinary_public_id"], name="media_app_m_cloudin_a52180_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="media_app_m_search__4852c3_gin"
            ),
        ),
    ]
