# Generated by Django 5.1 on 2026-05-09 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invitations", "0002_expand_invitation_roles_to_five"),
        ("members", "0006_add_email_index_to_investor_inquiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Internal label, e.g. 'May 2026 Training — Accra'", max_length=200
                    ),
                ),
                (
                    "slug_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID embedded in the public URL; unguessable.",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to instantly invalidate the QR code. Existing requests are preserved for review.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional hard expiry. Leave blank for no automatic expiry.",
                        null=True,
                    ),
                ),
                (
                    "max_submissions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional cap on total approved+pending submissions before auto-close. Leave blank for unlimited.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal admin notes (not shown publicly)."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Session",
                "verbose_name_plural": "Onboarding Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("job_title", models.CharField(max_length=200)),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("ipa_director", "IPA Director"),
                            ("ipa_manager", "IPA Manager"),
                            ("ipa_officer", "IPA Officer"),
                            ("ipa_data_entry", "IPA Data Entry"),
                            ("ipa_analyst", "IPA Analyst"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="IPA / ministry name (optional, often same as member state IPA).",
                        max_length=200,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved — Invitation Sent"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason shown to the applicant when rejected (optional).",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes — not sent to the applicant."
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address at time of submission.", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                (
                    "invitation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_request",
                        to="invitations.invitation",
                    ),
                ),
                (
                    "member_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboarding_requests",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_onboarding_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Which QR session this request came through.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="onboarding.onboardingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Request",
                "verbose_name_plural": "Onboarding Requests",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "submitted_at"], name="onboarding__status_f04b3f_idx"
                    ),
                    models.Index(fields=["email", "status"], name="onboarding__email_d0e678_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("email",),
                        name="unique_pending_onboarding_per_email",
                    )
                ],
            },
        ),
    ]
