# Generated by Django 5.1 on 2026-05-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_add_short_code_to_onboarding_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Personal email address (optional, in case work email changes).', max_length=254),
        ),
    ]
