# Generated by Django 5.1 on 2025-11-28 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberStateIPA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        help_text="Official country name (e.g., 'Nigeria')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version (e.g., 'nigeria')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 code (e.g., 'NGA')", max_length=3, unique=True
                    ),
                ),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True, help_text="Country flag emoji (e.g., '🇳🇬')", max_length=10
                    ),
                ),
                (
                    "ipa_full_name",
                    models.CharField(
                        help_text="Full IPA name (e.g., 'Nigerian Investment Promotion Commission')",
                        max_length=200,
                    ),
                ),
                (
                    "ipa_acronym",
                    models.CharField(help_text="IPA acronym (e.g., 'NIPC')", max_length=20),
                ),
                ("ipa_website", models.URLField(blank=True, help_text="Official IPA website")),
                (
                    "ipa_logo",
                    models.URLField(blank=True, help_text="IPA logo URL (AWS S3)", max_length=500),
                ),
                (
                    "overview",
                    models.TextField(blank=True, help_text="Country/IPA overview (300-500 words)"),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Compelling one-liner (e.g., 'Gateway to West Africa')",
                        max_length=200,
                    ),
                ),
                (
                    "population",
                    models.BigIntegerField(
                        help_text="Population count",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "population_display",
                    models.CharField(
                        blank=True,
                        help_text="Display format (e.g., '227M', '33.8M')",
                        max_length=20,
                    ),
                ),
                (
                    "gdp",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="GDP in USD billions",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gdp_display",
                    models.CharField(
                        blank=True,
                        help_text="Display format (e.g., '$252B', '$87.5B')",
                        max_length=20,
                    ),
                ),
                (
                    "gdp_growth_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GDP growth rate percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "gdp_per_capita",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GDP per capita in USD",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("capital_city", models.CharField(help_text="Capital city name", max_length=100)),
                (
                    "major_cities",
                    models.JSONField(blank=True, default=list, help_text="List of major cities"),
                ),
                (
                    "geographic_region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("west_coast", "West Coast"),
                            ("sahel", "Sahel"),
                            ("gulf_of_guinea", "Gulf of Guinea"),
                        ],
                        help_text="Regional classification",
                        max_length=50,
                    ),
                ),
                (
                    "official_language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("french", "French"),
                            ("portuguese", "Portuguese"),
                        ],
                        help_text="Official language",
                        max_length=50,
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(
                        help_text="Currency name (e.g., 'Nigerian Naira')", max_length=100
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(help_text="Currency code (e.g., 'NGN')", max_length=10),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        blank=True, help_text="Currency symbol (e.g., '₦')", max_length=10
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(help_text="Primary IPA contact email", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, help_text="Primary phone number", max_length=50),
                ),
                (
                    "physical_address",
                    models.TextField(blank=True, help_text="Complete physical address"),
                ),
                (
                    "office_hours",
                    models.CharField(
                        blank=True,
                        help_text="Office hours (e.g., 'Mon-Fri, 8:00 AM - 4:00 PM')",
                        max_length=200,
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                (
                    "hero_image",
                    models.URLField(
                        blank=True, help_text="Hero banner URL (1920x1080) (AWS S3)", max_length=500
                    ),
                ),
                (
                    "card_image",
                    models.URLField(
                        blank=True,
                        help_text="Card thumbnail URL (400x250) (AWS S3)",
                        max_length=500,
                    ),
                ),
                (
                    "ease_of_doing_business_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="World Bank ranking",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "competitiveness_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Global Competitiveness Index score",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        default="GMT", help_text="Time zone (e.g., 'GMT+1')", max_length=50
                    ),
                ),
                (
                    "investment_guide_pdf",
                    models.URLField(
                        blank=True,
                        help_text="Downloadable investment guide URL (AWS S3)",
                        max_length=500,
                    ),
                ),
                (
                    "doing_business_pdf",
                    models.URLField(
                        blank=True,
                        help_text="Doing Business guide PDF URL (AWS S3)",
                        max_length=500,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Set False for Mali, Niger, Burkina Faso"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Custom sort order (lower numbers first)"
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Featured on homepage or special sections"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Member State IPA",
                "verbose_name_plural": "Member State IPAs",
                "ordering": ["display_order", "country_name"],
                "indexes": [
                    models.Index(fields=["slug"], name="members_mem_slug_4323f2_idx"),
                    models.Index(fields=["country_code"], name="members_mem_country_121b75_idx"),
                    models.Index(
                        fields=["is_active", "country_name"], name="members_mem_is_acti_de6390_idx"
                    ),
                    models.Index(
                        fields=["is_active", "featured"], name="members_mem_is_acti_8e9df3_idx"
                    ),
                    models.Index(fields=["display_order"], name="members_mem_display_47a4fa_idx"),
                    models.Index(
                        fields=["official_language", "is_active"],
                        name="members_mem_officia_9ea2b1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IPAStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("position_title", models.CharField(max_length=200)),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Secretary/Director General"),
                            ("director", "Director"),
                            ("manager", "Manager"),
                            ("officer", "Officer"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.URLField(
                        blank=True, help_text="Staff photo URL (AWS S3)", max_length=500
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "show_on_website",
                    models.BooleanField(default=True, help_text="Display on public country page"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="members.memberstateipa",
                    ),
                ),
            ],
            options={
                "verbose_name": "IPA Staff Member",
                "verbose_name_plural": "IPA Staff Members",
                "ordering": ["member_state", "display_order", "full_name"],
                "indexes": [
                    models.Index(
                        fields=["member_state", "is_active"], name="members_ipa_member__e72b3c_idx"
                    ),
                    models.Index(
                        fields=["position_type", "is_active"], name="members_ipa_positio_f0a4c5_idx"
                    ),
                    models.Index(
                        fields=["member_state", "show_on_website"],
                        name="members_ipa_member__30cfc3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvestorInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("investment_opportunity", "Investment Opportunity"),
                            ("partnership", "Partnership Request"),
                            ("market_research", "Market Research"),
                            ("site_visit", "Site Visit Request"),
                            ("incentives", "Incentives Information"),
                            ("registration", "Business Registration"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Auto-generated (e.g., INQ-2025-0001)", max_length=50, unique=True
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("company_country", models.CharField(blank=True, max_length=100)),
                (
                    "estimated_investment",
                    models.CharField(blank=True, help_text="Investment range", max_length=100),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector_of_interest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="core.sector",
                    ),
                ),
                (
                    "member_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="members.memberstateipa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investor Inquiry",
                "verbose_name_plural": "Investor Inquiries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member_state", "status"], name="members_inv_member__cafbc9_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="members_inv_status_5e872c_idx"
                    ),
                    models.Index(
                        fields=["reference_number"], name="members_inv_referen_3be65f_idx"
                    ),
                    models.Index(
                        fields=["assigned_to", "status"], name="members_inv_assigne_56de9f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvestmentIncentive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Incentive name/title", max_length=200)),
                (
                    "incentive_type",
                    models.CharField(
                        choices=[
                            ("tax_holiday", "Tax Holiday"),
                            ("tax_credit", "Tax Credit"),
                            ("customs_exemption", "Customs Duty Exemption"),
                            ("vat_exemption", "VAT Exemption"),
                            ("capital_allowance", "Capital Allowance"),
                            ("free_zone", "Free Trade Zone Benefits"),
                            ("repatriation", "Profit Repatriation Guarantee"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the incentive"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Duration (e.g., '5-10 years', 'Ongoing')",
                        max_length=100,
                    ),
                ),
                (
                    "eligibility_criteria",
                    models.TextField(blank=True, help_text="Who qualifies for this incentive"),
                ),
                (
                    "benefit_amount",
                    models.CharField(
                        blank=True,
                        help_text="Quantifiable benefit (e.g., '100% tax exemption', '5% annual credit')",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_sectors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which sectors can benefit",
                        related_name="incentives",
                        to="core.sector",
                    ),
                ),
                (
                    "member_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incentives",
                        to="members.memberstateipa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investment Incentive",
                "verbose_name_plural": "Investment Incentives",
                "ordering": ["member_state", "display_order", "title"],
                "indexes": [
                    models.Index(
                        fields=["member_state", "incentive_type"],
                        name="members_inv_member__806cb9_idx",
                    ),
                    models.Index(
                        fields=["incentive_type", "is_active"],
                        name="members_inv_incenti_66ee21_idx",
                    ),
                    models.Index(
                        fields=["member_state", "display_order"],
                        name="members_inv_member__3b7a8f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FDIDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("fdi_inflow", "FDI Inflow"),
                            ("fdi_outflow", "FDI Outflow"),
                            ("fdi_stock", "FDI Stock"),
                            ("gdp", "GDP"),
                            ("trade_volume", "Trade Volume"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1990),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, help_text="Value in USD millions", max_digits=15
                    ),
                ),
                (
                    "value_display",
                    models.CharField(
                        blank=True, help_text="Formatted display value", max_length=50
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        help_text="Data source (e.g., 'UNCTAD', 'World Bank')",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fdi_data",
                        to="members.memberstateipa",
                    ),
                ),
            ],
            options={
                "verbose_name": "FDI Data Point",
                "verbose_name_plural": "FDI Data Points",
                "ordering": ["member_state", "data_type", "-year"],
                "indexes": [
                    models.Index(
                        fields=["member_state", "data_type", "year"],
                        name="members_fdi_member__3527fc_idx",
                    ),
                    models.Index(
                        fields=["validation_status", "-year"], name="members_fdi_validat_ca30db_idx"
                    ),
                    models.Index(
                        fields=["data_type", "-year"], name="members_fdi_data_ty_5371d1_idx"
                    ),
                ],
                "unique_together": {("member_state", "data_type", "year")},
            },
        ),
        migrations.CreateModel(
            name="MemberStateSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_priority",
                    models.BooleanField(
                        default=False, help_text="Is this a priority sector for this country?"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Country-specific sector description"),
                ),
                (
                    "investment_potential",
                    models.TextField(
                        blank=True, help_text="Investment opportunities in this sector"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "member_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_states",
                        to="core.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member State Sector",
                "verbose_name_plural": "Member State Sectors",
                "ordering": ["member_state", "display_order", "sector__name"],
                "indexes": [
                    models.Index(
                        fields=["member_state", "is_priority"],
                        name="members_mem_member__0bbe8c_idx",
                    ),
                    models.Index(
                        fields=["sector", "is_priority"], name="members_mem_sector__e99ebb_idx"
                    ),
                    models.Index(
                        fields=["member_state", "display_order"],
                        name="members_mem_member__23e25b_idx",
                    ),
                ],
                "unique_together": {("member_state", "sector")},
            },
        ),
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Success story headline", max_length=200)),
                (
                    "company_name",
                    models.CharField(help_text="Investing company name", max_length=200),
                ),
                (
                    "company_origin",
                    models.CharField(
                        blank=True, help_text="Company's country of origin", max_length=100
                    ),
                ),
                (
                    "investment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Investment amount in USD",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "investment_amount_display",
                    models.CharField(
                        blank=True,
                        help_text="Display format (e.g., '$50M', '$2.5B')",
                        max_length=50,
                    ),
                ),
                (
                    "jobs_created",
                    models.IntegerField(blank=True, help_text="Number of jobs created", null=True),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Year of investment",
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                ("summary", models.TextField(help_text="Brief summary (2-3 sentences)")),
                ("full_story", models.TextField(blank=True, help_text="Complete success story")),
                ("impact", models.TextField(blank=True, help_text="Economic/social impact")),
                (
                    "image",
                    models.URLField(
                        blank=True, help_text="Company/project image URL (AWS S3)", max_length=500
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_stories",
                        to="members.memberstateipa",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="success_stories",
                        to="core.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Success Story",
                "verbose_name_plural": "Success Stories",
                "ordering": ["member_state", "-featured", "display_order", "-year"],
                "indexes": [
                    models.Index(
                        fields=["member_state", "published"], name="members_suc_member__d0294a_idx"
                    ),
                    models.Index(
                        fields=["sector", "published"], name="members_suc_sector__bde484_idx"
                    ),
                    models.Index(
                        fields=["featured", "-year"], name="members_suc_feature_1a7692_idx"
                    ),
                    models.Index(fields=["-year", "published"], name="members_suc_year_0b59a2_idx"),
                ],
            },
        ),
    ]
