# Generated by Django 5.1 on 2025-12-17 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberstateipa",
            name="corporate_tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Corporate tax rate (%)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="days_to_start_business",
            field=models.IntegerField(
                blank=True,
                help_text="Days to start a business",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="electricity_access",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Electricity access (%)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="fdi_inflows",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="FDI inflows in USD millions",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="inflation_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Inflation rate (%)",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(-50)],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="internet_penetration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Internet penetration (%)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="key_industries",
            field=models.TextField(blank=True, help_text="Key industries (comma-separated)"),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="literacy_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Literacy rate (%)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="median_age",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Median age in years",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="number_of_airports",
            field=models.IntegerField(
                blank=True,
                help_text="Number of airports",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="paved_roads_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Paved roads (%)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="population_growth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Population growth rate (%)",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(-10)],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="total_exports",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total exports in USD millions",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="total_imports",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total imports in USD millions",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="trade_agreements",
            field=models.TextField(blank=True, help_text="Trade agreements (comma-separated)"),
        ),
        migrations.AddField(
            model_name="memberstateipa",
            name="urbanization_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Urbanization rate (%)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
