# Generated by Django 5.1 on 2026-02-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_memberstateipa_corporate_tax_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ECOWASLeadershipPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("commission_president", "President of ECOWAS Commission"),
                            (
                                "commissioner_economic",
                                "Commissioner for Economic Affairs and Agriculture",
                            ),
                            (
                                "authority_chairman",
                                "Chairman of ECOWAS Authority of Heads of State",
                            ),
                            ("resident_rep", "ECOWAS Resident Representative"),
                        ],
                        help_text="Type of ECOWAS position",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "position_title",
                    models.CharField(help_text="Official title of position", max_length=200),
                ),
                (
                    "position_description",
                    models.TextField(
                        blank=True, help_text="Description of role and responsibilities"
                    ),
                ),
                (
                    "current_holder_name",
                    models.CharField(
                        help_text="Full name of current position holder", max_length=200
                    ),
                ),
                (
                    "current_holder_title_prefix",
                    models.CharField(
                        blank=True, help_text="Title prefix (H.E., Dr., etc.)", max_length=50
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(help_text="Country of origin/nationality", max_length=100),
                ),
                (
                    "official_portrait",
                    models.URLField(
                        blank=True,
                        help_text="Official portrait - Min 1200x1500px, Max 3MB",
                        max_length=500,
                    ),
                ),
                (
                    "biography",
                    models.TextField(help_text="Comprehensive biography (500-800 words)"),
                ),
                ("education", models.TextField(blank=True, help_text="Educational background")),
                (
                    "career_highlights",
                    models.TextField(
                        blank=True, help_text="Major career achievements before current position"
                    ),
                ),
                (
                    "vision_statement",
                    models.TextField(
                        blank=True, help_text="Vision for regional integration and ECOWAS"
                    ),
                ),
                ("start_date", models.DateField(help_text="Start date of current tenure")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End date of tenure (null if ongoing)", null=True
                    ),
                ),
                ("office_email", models.EmailField(blank=True, max_length=254)),
                ("office_phone", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this the current holder of the position?"
                    ),
                ),
            ],
            options={
                "verbose_name": "ECOWAS Leadership Position",
                "verbose_name_plural": "ECOWAS Leadership Positions",
                "ordering": ["position_type"],
            },
        ),
        migrations.CreateModel(
            name="IPALeadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full official name (e.g., Dr. Hinga Sandi)", max_length=200
                    ),
                ),
                (
                    "official_title",
                    models.CharField(
                        choices=[
                            ("ceo", "Chief Executive Officer (CEO)"),
                            ("dg", "Director-General (DG)"),
                            ("ed", "Executive Director (ED)"),
                            ("md", "Managing Director (MD)"),
                            ("commissioner", "Commissioner"),
                        ],
                        help_text="Official designation",
                        max_length=20,
                    ),
                ),
                (
                    "official_photograph",
                    models.URLField(
                        blank=True,
                        help_text="Professional headshot - Min 800x1000px, Max 2MB, neutral background",
                        max_length=500,
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True,
                        help_text="Professional biography (200-500 words covering education, career, vision)",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(
                        blank=True, help_text="Date of appointment to current position", null=True
                    ),
                ),
                (
                    "direct_email",
                    models.EmailField(
                        blank=True, help_text="Direct email (if publicly available)", max_length=254
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_verified",
                    models.DateField(
                        blank=True, help_text="Date when information was last verified", null=True
                    ),
                ),
                (
                    "member_state",
                    models.OneToOneField(
                        help_text="Member state this leader represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipa_leadership",
                        to="members.memberstateipa",
                    ),
                ),
            ],
            options={
                "verbose_name": "IPA Leader",
                "verbose_name_plural": "IPA Leaders",
                "ordering": ["member_state__country_name"],
            },
        ),
    ]
