# Generated by Django 5.1 on 2026-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_ecowasleadershipposition_ipaleadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstateipa',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for search engines (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Page title for search engines (max 60 chars)', max_length=60),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing', max_length=300),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='Open Graph image URL for social sharing', max_length=500),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=100),
        ),
    ]
