# Generated by Django 5.2.5 on 2026-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_add_seo_fields_to_memberstateipa'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstateipa',
            name='incentives_brochure_pdf',
            field=models.URLField(blank=True, help_text='Investment incentives brochure URL', max_length=500),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='infrastructure_report_pdf',
            field=models.URLField(blank=True, help_text='Infrastructure and logistics report URL', max_length=500),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='legal_framework_pdf',
            field=models.URLField(blank=True, help_text='Legal and regulatory framework document URL', max_length=500),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='sector_profiles_pdf',
            field=models.URLField(blank=True, help_text='Sector profiles document URL', max_length=500),
        ),
    ]
