# Generated by Django 5.1 on 2026-05-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_add_additional_resource_pdf_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investorinquiry",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
