# Generated by Django 5.1 on 2026-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_rename_sliepa_to_national_investment_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentincentive",
            name="document_name",
            field=models.CharField(
                blank=True, help_text="Original filename of the uploaded document", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="investmentincentive",
            name="document_url",
            field=models.URLField(
                blank=True,
                help_text="Supporting document URL (uploaded to Cloudinary)",
                max_length=500,
            ),
        ),
    ]
