# Generated by Django 5.1 on 2026-05-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
        ('members', '0009_add_document_to_investmentincentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentincentive',
            name='document_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_documents', to='media_app.mediafile'),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='card_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_member_states', to='media_app.mediafile'),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='hero_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_member_states', to='media_app.mediafile'),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='ipa_logo_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_member_states', to='media_app.mediafile'),
        ),
        migrations.AddField(
            model_name='memberstateipa',
            name='storage_quota_bytes',
            field=models.BigIntegerField(default=1073741824, help_text='Media library quota in bytes (default 1 GB)'),
        ),
    ]
