# Generated by Django 5.1 on 2026-05-09 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Full Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email Address")),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, verbose_name="Organization"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "job_title",
                    models.CharField(blank=True, max_length=200, verbose_name="Job Title"),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("registered", "Registered"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Email Sent At"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Registered At"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Training Invitation",
                "verbose_name_plural": "Training Invitations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PreTrainingAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "current_role",
                    models.CharField(
                        choices=[
                            ("", "Select your role…"),
                            ("director_general", "Director General / CEO"),
                            ("director", "Director"),
                            ("manager", "Manager"),
                            ("analyst", "Analyst / Officer"),
                            ("specialist", "Specialist / Advisor"),
                            ("coordinator", "Coordinator"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Current Role",
                    ),
                ),
                (
                    "years_in_role",
                    models.CharField(
                        choices=[
                            ("", "Select…"),
                            ("0-1", "Less than 1 year"),
                            ("1-3", "1–3 years"),
                            ("3-5", "3–5 years"),
                            ("5-10", "5–10 years"),
                            ("10+", "More than 10 years"),
                        ],
                        max_length=10,
                        verbose_name="Years in Role",
                    ),
                ),
                (
                    "knowledge_ipawas",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1 = None at all, 5 = Expert",
                        verbose_name="Knowledge of IPAWAS Platform",
                    ),
                ),
                (
                    "knowledge_investment_promotion",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1 = Beginner, 5 = Expert",
                        verbose_name="Investment Promotion Skills",
                    ),
                ),
                (
                    "knowledge_data_tools",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1 = None at all, 5 = Expert",
                        verbose_name="Data & Digital Tools Proficiency",
                    ),
                ),
                (
                    "knowledge_regional_collab",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1 = No experience, 5 = Extensive",
                        verbose_name="Regional Collaboration Experience",
                    ),
                ),
                (
                    "training_expectations",
                    models.TextField(
                        help_text="What do you hope to achieve from this training?",
                        verbose_name="Training Expectations",
                    ),
                ),
                (
                    "challenging_areas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Select all that apply",
                        verbose_name="Challenging Areas",
                    ),
                ),
                (
                    "prior_ipawas_experience",
                    models.TextField(
                        blank=True,
                        help_text="Describe any experience you have with the IPAWAS platform (leave blank if none).",
                        verbose_name="Prior IPAWAS Experience",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_assessment",
                        to="training.traininginvitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Training Assessment",
                "verbose_name_plural": "Pre-Training Assessments",
            },
        ),
        migrations.CreateModel(
            name="PostTrainingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Overall Training Rating",
                    ),
                ),
                (
                    "content_relevance",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Content Relevance to My Work",
                    ),
                ),
                (
                    "trainer_effectiveness",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Facilitator Effectiveness",
                    ),
                ),
                (
                    "platform_usability",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="IPAWAS Platform Usability",
                    ),
                ),
                (
                    "pace_and_structure",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Pace & Structure of the Training",
                    ),
                ),
                (
                    "most_valuable",
                    models.TextField(
                        help_text="What was the most valuable part of this training for you?",
                        verbose_name="Most Valuable Element",
                    ),
                ),
                (
                    "needs_improvement",
                    models.TextField(
                        help_text="What could be improved in future sessions?",
                        verbose_name="Areas for Improvement",
                    ),
                ),
                (
                    "key_takeaway",
                    models.TextField(
                        help_text="Describe one concrete action you will take as a result of this training.",
                        verbose_name="Key Takeaway",
                    ),
                ),
                (
                    "apply_learning_timeline",
                    models.CharField(
                        choices=[
                            ("", "Select…"),
                            ("immediately", "Immediately (within 1 week)"),
                            ("soon", "Within 1 month"),
                            ("quarter", "Within 3 months"),
                            ("unsure", "Unsure"),
                        ],
                        max_length=15,
                        verbose_name="When Will You Apply What You Learned?",
                    ),
                ),
                (
                    "would_recommend",
                    models.BooleanField(verbose_name="Would Recommend to a Colleague"),
                ),
                (
                    "additional_comments",
                    models.TextField(blank=True, verbose_name="Additional Comments"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_feedback",
                        to="training.traininginvitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post-Training Feedback",
                "verbose_name_plural": "Post-Training Feedback",
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Session Title")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("training_date", models.DateField(verbose_name="Training Date")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location / Platform"
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("pre", "Pre-Training Assessment"),
                            ("post", "Post-Training Feedback"),
                        ],
                        default="pre",
                        help_text="Switch to Post-Training after the training is complete.",
                        max_length=4,
                        verbose_name="Current Phase",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active sessions accept new responses.",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Session",
                "verbose_name_plural": "Training Sessions",
                "ordering": ["-training_date"],
            },
        ),
        migrations.AddField(
            model_name="traininginvitation",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="training.trainingsession",
                verbose_name="Training Session",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="traininginvitation",
            unique_together={("session", "email")},
        ),
    ]
